### ISSUE TITLE
It just does not work.

### ISSUE THREAD

**Issue by PuciekTM** [Otiel/BandcampDownloader#1]
It dowloades empty files. Please update.

**Comment by Jorthmo** [comment]
Agreed! Please fix this :(

**Comment by Otiel** [comment]
Will have to look at it when I find the time, hopefully soon!

**Comment by PuciekTM** [comment]
This shold help: 
// ==UserScript==
// @name Bandcamp Downloader
// @author Tommy Smith
// @description Download songs from Bandcamp free of charge!
// @version 1.4
// @include http*://*.bandcamp.com
// @include http*://*.bandcamp.com/
// @include http*://bandcamp.com/album/*
// @include http*://*.bandcamp.com/album/*
// @include http*://bandcamp.com/track/*
// @include http*://*.bandcamp.com/track/*
// @include http*://disasterpeace.com/album/*
// @include http*://*.disasterpeace.com/album/*
// @include http*://disasterpeace.com/track/*
// @include http*://*.disasterpeace.com/track/*
// @include http*://derekpalmermusic.com/album/*
// @include http*://*.derekpalmermusic.com/album/*
// @include http*://derekpalmermusic.com/track/*
// @include http*://*.derekpalmermusic.com/track/*
// @exclude http*://*.facebook.com/*
// ==/UserScript==

// temporary workaround while I try to figure out what is erasing my link...
window.setTimeout(function() {
// create the button to trigger Bandcamp Downloader
var script = document.createElement('script');
script.type = "text/javascript";
script.innerHTML = function(){/*
function step() {
document.getElementById("bandcampdownloaderbutton").href="javascript:";
document.getElementById("bandcampdownloaderbutton").style.color="gray";
for (track in TralbumData.trackinfo) {
for (enc in TralbumData.trackinfo[track]["file"]) {
if (!document.getElementsByClassName("dl_link")[track]) {
if (!document.getElementById("track_table")) {
window.location=TralbumData.trackinfo[track]["file"][enc];
break;
}
} else {
document.getElementsByClassName("dl_link")[track].innerHTML += "-<a href='"+TralbumData.trackinfo[track]["file"][enc]+"'>"+enc+"</a>";
if (document.getElementsByClassName("dl_link")[track].innerHTML[0] == "-") {
document.getElementsByClassName("dl_link")[track].innerHTML = document.getElementsByClassName("dl_link")[track].innerHTML.substring(1);
}
}
}
}
}*/}.toString().slice(14,-3)
document.getElementsByTagName('body')[0].appendChild(script);

// Tidy it up and make it look all nice, since this must be done after the tracks load

if (!document.getElementsByClassName("ft compound-button")[0]) {
console.log("A rare error has occured - \"Buy Now\" button was not found. Please try again later or contact the script owner (Tommy Smith)");
} else {
document.getElementsByClassName("ft compound-button")[0].innerHTML="<a href='javascript:step();' id='bandcampdownloaderbutton'>Use Bandcamp Downloader</a> or "+document.getElementsByClassName("ft compound-button")[0].innerHTML;
}
}, 250);

**Comment by beppe9000** [comment]
Also my own tool stopped working...

**Comment by beppe9000** [comment]
@PuciekTM 
@Jorthmo 

I also compiled the fixed version. It is available here:
https://github.com/beppe9000/BandcampDownloader/releases/tag/v0.1.4.2

**Comment by Otiel** [comment]
Thanks a lot @beppe9000 !

The issue is fixed, I have also released a [new version](https://github.com/Otiel/BandcampDownloader/releases) on this repo where you can download the binaries.

**Comment by Jorthmo** [comment]
Thank you!, Will come in handy when I need it again, I have been using a
spotify Downloader in the mean time which has been working fine, but Tyvm
for the fix.

**Comment by beppe9000** [comment]
You are welcome
