### ISSUE TITLE
Do not download albums with no track

### ISSUE THREAD

**Issue by Otiel** [Otiel/BandcampDownloader#106]
Example: https://adhesivesounds.bandcamp.com/album/terme

**Comment by wilbishardis** [comment]
Hi, I'm looking to start contributing to OSS - do you mind if I have a go at fixing this?

Thanks.

**Comment by Otiel** [comment]
Sure, let me know if you need help!

**Comment by wilbishardis** [comment]
Thanks! Pull request #108 opened.

**Comment by Otiel** [comment]
Released in [1.1.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.1.0). Thanks for your contribution!
