### ISSUE TITLE
Cannot check for updates

### ISSUE THREAD

**Issue by Otiel** [Otiel/BandcampDownloader#109]
>I don't know does this matter, but it also says cannot check for updates in bottom left corner.

_Originally posted by @AKmatiAK in https://github.com/Otiel/BandcampDownloader/issues/107#issuecomment-501343865_

**Comment by Otiel** [comment]
@AKmatiAK 

What happens if you click "Check now" from the Settings window?

![image](https://user-images.githubusercontent.com/3851902/59375614-d0b50300-8d4e-11e9-84d7-0849d9e4c15f.png)

**Comment by AKmatiAK** [comment]
same.
![Bez tytułu](https://user-images.githubusercontent.com/51701971/59379377-ba12aa00-8d56-11e9-9ceb-f7a557b53332.png)

**Comment by Otiel** [comment]
Thanks.

I've finally found where the issue came from. I will soon release a new version with a fix.

**Comment by Otiel** [comment]
Can you try the new version [1.1.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.1.0) and let me know if you can check for updates now?
