### ISSUE TITLE
Resume partial/aborted downloads

### ISSUE THREAD

**Issue by servix** [Otiel/BandcampDownloader#11]
Hi,

It will be great to have the resume possibility in case of a network/internet interruption or some other cosmic disruption in the download process.
I've recently leave a download list from an URL (a single URL with several albums), and in the middle of the process it stopped, without errors, maybe because of an internet link interruption or IP change from the ISP.
In such case, if I start the process again, the already downloaded content (full or partial) gets deleted and overwritten, instead of keeping the content successfully downloaded, and resuming the partial downloads.
At least, having the possibility to check the content already OK and continue or start over only the broken files, will be absolutely great.

Thanks in advance, and go ahead! great project!

**Comment by Otiel** [comment]
That's a good idea. I'll have to think of ways on how to check if an existing file is complete without being forced to download it once more.

**Comment by servix** [comment]
Great! Let me know if you need to perform some testing...

**Comment by ajsnyde** [comment]
@Otiel I can take this task out too, if needed.

**Comment by Otiel** [comment]
@ajsnyde Please do if you want!

**Comment by ajsnyde** [comment]
See https://github.com/ajsnyde/BandcampDownloader/commit/72c442f657484ec3b79b7f30d28abec0a3d644bd
<blockquote>Added functionality that checks for existing files before downloading…
…. The filesizes are then compared, with some wiggle room to account for the addition of album covers and metadata. The default of AllowableFileSizeDifference is .05, but can be set to 0.00 to disable the functionality entirely, or 1.00 to simply check for filename existence. Like other changes I've made, you'll have to save settings to a file and then manually change values.</blockquote>

**Comment by Otiel** [comment]
I've released a [new version](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.5.2) with @ajsnyde changes.
