### ISSUE TITLE
Download songs under an artist/album folder architecture

### ISSUE THREAD

**Issue by deadmans96** [Otiel/BandcampDownloader#12]
How could i make the downloader automatically download songs and put every album in a folder with respect to Artist name

**Comment by Otiel** [comment]
This would require a change in the code. I'll see what I can do when I find the time. Thanks for the idea!

**Comment by ajsnyde** [comment]
Otiel, if you are okay with it, I could create this feature for you in a separate branch. I've doing something similar with a downloader of my own.

**Comment by ajsnyde** [comment]
I've added the functionality that alleviates this issue. See below:
https://github.com/Otiel/BandcampDownloader/pull/14
https://github.com/ajsnyde/BandcampDownloader

Let me know if this works as a solution, @deadmans96 .

**Comment by 07416** [comment]
@deadmans96 Do you mean that album folders should be named "Nirvana - Nevermind" instead of "Nevermind"? I would love that too.

**Comment by ajsnyde** [comment]
@07416  With my addition, you could use that naming scheme. For example, setting the directory to the following would achieve your desired result.
C:\Users\Username\Desktop\{artist} - {album}
Which would resolve to:
C:\Users\Username\Desktop\Nirvana - Nevermind

Does this make sense? Do you have any questions? This hasn't been officially merged with @Otiel 's master branch yet, so you'll need to compile using my branch, as seen in my earlier comment.

**Comment by Otiel** [comment]
I've released a [new version](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.5.2) with @ajsnyde changes.

**Comment by deadmans96** [comment]
hey otiel
may be i made a conflict :D , my argument was to make the program make folders automactily not by myself like Deezloader or old SpotifyPlaylist Downloader
the program grab Album name & Artist and make the folder scheme like i mentioned before
if you did it may be i didn't see the function yet :D

**Comment by Otiel** [comment]
@deadmans96 Did you try setting the save path to `C:\BandcampDownloader\{artist}\{album}`?

**Comment by deadmans96** [comment]
@Otiel  no i just set default folder for all coming songs
is it necessery !?

**Comment by Otiel** [comment]
@deadmans96 Yes it is necessary if you want the behavior you're asking for. Try it and let know how that works for you.

**Comment by deadmans96** [comment]
@Otiel  Wonderful , i was in doubt with this statement :D \{artist} - {album} :D
