### ISSUE TITLE
"Could not retrieve data"

### ISSUE THREAD

**Issue by Flanker-305** [Otiel/BandcampDownloader#120]
Hi all,

newbie here - no programming experience whatsoever - so please bear with me as a noob plz :)
I found the BCD here and it worked all fine for quite some time.

However, I cannot download playlists. Is this possible?
I tried a lot of different things but it doesn't work.
For example: I would like to download this list: https://soundcloud.com/flanker305/sets/dl
Gets me [this](https://i.imgur.com/1uejzXH.png) message.

Any help is much appreciated - let me know if there is anymore info I can provide.

Thanks in advance!

Flanker

**Comment by Otiel** [comment]
Hi,

_BandcampDownloader_ is for [bandcamp.com](https://bandcamp.com) only, it doesn't support [soundcloud.com](https://soundcloud.com). 🙂

**Comment by Flanker-305** [comment]
> Hi,
> 
> _BandcampDownloader_ is for [bandcamp.com](https://bandcamp.com) only, it doesn't support [soundcloud.com](https://soundcloud.com). 🙂

This is ridiculous - I messed it all up. Sorry! thanks - I will delete this when you've read it. :)

**Comment by Otiel** [comment]
No worries. 🙂 

I will simply close this issue, no need to delete. This could help other persons in the confusion happens for them as well.

**Comment by Flanker-305** [comment]
> No worries. 🙂
> 
> I will simply close this issue, no need to delete. This could help other persons in the confusion happens for them as well.

Allright - THANK you. While we're on the subject: a tool for downloading entire playlists from Soundcloud would be very handy. There are a few around, but they don't work as flawlessly as the BCD here. Probably why I mixed them up :)
Do you know a way to make this happen?

**Comment by Otiel** [comment]
I haven't tried them myself, but there are a few that seem popular on GitHub: https://github.com/search?q=soundcloud+downloader&type=Repositories

**Comment by Flanker-305** [comment]
> I haven't tried them myself, but there are a few that seem popular on GitHub: https://github.com/search?q=soundcloud+downloader&type=Repositories
> 
> (some even support SoundCloud _and_ Bandcamp)

Awesome! Gonna check that out. In the meantime I found [this,](https://addoncrop.com/soundcloud-music-downloader/) which works great so far. :)
