### ISSUE TITLE
Watch for clipboard link feature-request

### ISSUE THREAD

**Issue by l0oo** [Otiel/BandcampDownloader#126]
Hello!
I'd like to add new feature: watch for clipboard link.
As I like to read blogs where good BC albums are mentioned, I have to copy its adress to clipboard, than paste to BCDownloader and press download... Could you make optional "watch for clipboard link" => when I copy BC link to clipboard it is automatically transferred to BCDownloader and than download in background... What do you think? Hope it is possible...

**Comment by Otiel** [comment]
Duplicate #85 

Sorry, no time to work on this right now. I haven't ruled this out though, but it requires some thinking before.
