### ISSUE TITLE
"Could not retrieve data" & "Could not check for updates"

### ISSUE THREAD

**Issue by Norio45** [Otiel/BandcampDownloader#132]
I've tried to download an album many many times but it keep saying
"Could not retrieve data for..."
and after that it said "Could not check for updates"
also it's the latest version (1.3.1)
did something wrong with the program?

**Comment by Otiel** [comment]
Not to my knowledge. It sounds more like a problem on your Internet connection.

**Comment by Norio45** [comment]
my Internet Connection is fine or i did something wrong?

**Comment by Otiel** [comment]
Can you try to:
* Go to https://github.com/Otiel/BandcampDownloader/releases/latest in your browser.
* Then click on `Settings → General → Check now` in _BandcampDownloader_.

What happens?

**Comment by Norio45** [comment]
here
![Bandcamp Downloader 20_2_2563 17_38_49](https://user-images.githubusercontent.com/61272726/74926080-e9120d00-5407-11ea-9c8c-9ff75529a8ee.png)

**Comment by Otiel** [comment]
Do you still have the message "Could not check for updates" after restarting _BandcampDownloader_?

**Comment by Norio45** [comment]
no but it still can't download an album

**Comment by Otiel** [comment]
Can you upload the `BandcampDownloader.log` file?

**Comment by Norio45** [comment]
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/4230302/BandcampDownloader.log)

**Comment by Otiel** [comment]
Weird. And you can go to https://reflections.bandcamp.com/album/willow in your browser without issue?

**Comment by Norio45** [comment]
yes

**Comment by Otiel** [comment]
Is this the only URL causing an issue, or do you get the same error message for any bandcamp URL?

**Comment by Norio45** [comment]
No but everything seem fine now, i can download most album now.
I don't know if it caused by URL but right now it work perfectly fine.
I will tell you if there's any problem in tomorrow

**Comment by Norio45** [comment]
Alright nvm it happend again still the same problem

**Comment by Otiel** [comment]
Can you upload your _BandcampDownloader.ini_ file?

**Comment by Norio45** [comment]
[BandcampDownloader.txt](https://github.com/Otiel/BandcampDownloader/files/4231185/BandcampDownloader.txt)

**Comment by Otiel** [comment]
Thanks, you don't seem to have changed any setting than could cause an issue.

What I find weird though, is the content of your log file, which is surprisingly empty. You should at least have some lines like:

```
2020-02-20 15:26:39.5066  INFO   Computing size for album "Willow"...
2020-02-20 15:26:39.7722  DEBUG  Retrieved the size of the cover art file for album "Willow"
2020-02-20 15:26:40.0323  DEBUG  Retrieved the size of the MP3 file for the track "Synthetics"
...
```

Did you upload your whole log file without stripping it of some content?

**Comment by Norio45** [comment]
no or you mean "BandcampDownloader.log"?

**Comment by Otiel** [comment]
Yes that's what I meant.

It may be bandcamp.com that blacklisted your IP temporarily because you previously downloaded lots of album. Did you?

**Comment by Norio45** [comment]
about 90+ albums so yeah

**Comment by Otiel** [comment]
Indeed, that's a lot. 😄 

I think that's probably the reason then.

**Comment by Norio45** [comment]
anyway i guess i'll wait
also thanks for your help hope you have a nice day :)

**Comment by Otiel** [comment]
Thanks, you as well.

Let me know if it works correctly after you'll have waited some time (I guess at least some hours, maybe a day or two - but that's just a guess, I don't know the bandcamp.com blacklist policy). Good luck!
