### ISSUE TITLE
Альбомы не сортируются по папкам

### ISSUE THREAD

**Issue by TheWishMaster123123** [Otiel/BandcampDownloader#136]
Сабж, При выкачке дискографии все файлы лежат в куче, что сводит к нулю преимущества данной функции. Как для альбома создать отдельную папку?

**Comment by Otiel** [comment]
Use `{artist}` and `{album}` placeholders in `Сохранить альбомы в`:

![Untitled](https://user-images.githubusercontent.com/3851902/79215263-9c691200-7e4b-11ea-968e-32901390ff69.png)

**Comment by TheWishMaster123123** [comment]
Дык оно все равно все файлы в одну папку сохраняет, даже если скачиваешь дискографию.

-- реклама -----------------------------------------------------------
Как оставаться проактивным и не выгореть на домашнем?
https://bit.ly/3cadxOW

**Comment by Otiel** [comment]
Can you share the content of your `BandcampDownloader.ini` file?

**Comment by TheWishMaster123123** [comment]
DownloadsPath=c:\Users\РЎРµСЂРіРµР№\Downloads\
DownloadArtistDiscography=true
AllowedFileSizeDifference=0.05
DownloadMaxTries=7
DownloadRetryCooldown=0.2
DownloadRetryExponent=4
SaveCoverArtInFolder=true
CoverArtFileNameFormat={album}
CoverArtInFolderConvertToJpg=true
CoverArtInFolderResize=false
CoverArtInFolderMaxSize=1000
SaveCoverArtInTags=true
CoverArtInTagsConvertToJpg=true
CoverArtInTagsResize=true
CoverArtInTagsMaxSize=1000
DownloadOneAlbumAtATime=false
RetrieveFilesSize=true
CheckForUpdates=true
EnableApplicationSounds=false
ShowVerboseLog=false
Language=ru
Theme=Light
Proxy=System
ProxyHttpAddress=
ProxyHttpPort=0
CreatePlaylist=false
M3uExtended=true
PlaylistFormat=m3u
PlaylistFileNameFormat={album}
FileNameFormat={tracknum} {artist} - {year} {album} - {title}.mp3
ModifyTags=true
TagAlbumArtist=Modify
TagAlbumTitle=Modify
TagArtist=Modify
TagComments=Empty
TagLyrics=Modify
TagTrackNumber=Modify
TagTrackTitle=Modify
TagYear=Modify


-- реклама -----------------------------------------------------------
Как оставаться проактивным и не выгореть на домашнем?
https://bit.ly/3cadxOW

**Comment by Otiel** [comment]
>`DownloadsPath=c:\Users\РЎРµСЂРіРµР№\Downloads\`

It seems you didn't use the `{artist}` and `{album}` placeholders. Can you change your `Сохранить альбомы в` to `c:\Users\РЎРµСЂРіРµР№\Downloads\{artist}\{album}` and try again?

**Comment by TheWishMaster123123** [comment]
О! Спасибо.


-- реклама -----------------------------------------------------------
Как оставаться проактивным и не выгореть на домашнем?
https://bit.ly/3cadxOW
