### ISSUE TITLE
How to start it? :I

### ISSUE THREAD

**Issue by OlMi1** [Otiel/BandcampDownloader#138]
So I tried with node.js (npm start) but it didn´t do anything and just gave errors... how to start it?

**Comment by Otiel** [comment]
This is a .NET application. Just run the `BandcampDownloader.exe` file.

**Comment by OlMi1** [comment]
Well I Downloaded via "clone or download" but there is no exe!

**Comment by AKmatiAK** [comment]
https://github.com/Otiel/BandcampDownloader/releases/latest

**Comment by Otiel** [comment]
"Clone or download" is used to get the source code. If you want to simply use the application, download the "BandcampDownloader.zip" file from the releases page linked by @AKmatiAK:

![Untitled](https://user-images.githubusercontent.com/3851902/79889659-a5835180-83fe-11ea-9088-d7c1b7028c91.png)
