### ISSUE TITLE
Single's release year tag is always "1".

### ISSUE THREAD

**Issue by MpKTO** [Otiel/BandcampDownloader#144]
Alboms contained only one song (Single), have their "relese year" tag set to "1"
For example downloading this:
> https://pensees.bandcamp.com/
> https://shahmusic.bandcamp.com/
> https://deniskilty.bandcamp.com/music

![image](https://user-images.githubusercontent.com/25183693/86598070-449efa80-bfa5-11ea-94cf-636839a1fd13.png)

If "relese year" really not present in song info, try to take it from bandcamp itself. From "datePublished" meta info.
![Year](https://user-images.githubusercontent.com/25183693/86600553-deb47200-bfa8-11ea-818a-42ff5fca8dd7.png)

Downloader Version: 1.3.1

**Comment by Nebula-Mechanica** [comment]
The trouble seems to be that _album_release_date_ property in json is set to _null_ for singles. It seems though, that _current_ -> _release_date_ is filled, so we can take date from there, if _album_release_date_ is _null_.

**Comment by Nebula-Mechanica** [comment]
Created a pull request with fix: https://github.com/Otiel/BandcampDownloader/pull/145

**Comment by Otiel** [comment]
Thanks, I will have a look asap.

**Comment by Otiel** [comment]
Fixed in [v1.3.2](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.3.2), thanks to @Nebula-Mechanica!
