### ISSUE TITLE
Bandcamp downloader failed to download discography

### ISSUE THREAD

**Issue by Purplepanther1234** [Otiel/BandcampDownloader#150]
This happens while also trying to download single albums as well
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/5158616/BandcampDownloader.log)

**Comment by charlespctech** [comment]
I am having the same issue.

"2020-09-02 12:37:47.5276  INFO   Starting download...
2020-09-02 12:37:47.6196  INFO   Retrieving artist discography from https://machinedrum.bandcamp.com/
2020-09-02 12:37:48.3227  ERROR  No discography could be found on https://machinedrum.bandcamp.com/. Try to uncheck the "Download artist discography" option
"

**Comment by Otiel** [comment]
Thanks for reporting this.

Bandcamp has changed their metadata, so I'll have to find another way to discover the discography.

**Comment by buzniak** [comment]
Was going to leave the same comment, but you're on it Otiel! Hope you find a solution soon, love this app to death, AMAZING!

**Comment by jundivision** [comment]
Came here with regards to the same problem. Thanks for all your work, look forward to the update!

**Comment by Nebula-Mechanica** [comment]
Hello!

@Otiel , I have created pull request in attempt to fix this bug: https://github.com/Otiel/BandcampDownloader/pull/152

**Comment by wondergirlAmazon** [comment]
I thought i was doing something wrong , look forward to the fix :)

**Comment by Nariod14** [comment]
Having the same issue, but all i did was use idm to download all links and in the list check all the album links and click "copy to clipboard" then just paste them in the app. Bandage fix but it works!

**Comment by FininhoRn** [comment]
In version 1.3.3 the problem persists.

**Comment by Otiel** [comment]
Fix is coming in the next version.

**Comment by Tharn** [comment]
Having the same issue with whole artist discographies without an album URL.

**Comment by spacesynth2020** [comment]
please fix bandcamp discography download please

**Comment by Mrakobes666** [comment]
please!

**Comment by spacesynth2020** [comment]
So how to download full discography please?

Sent from Yahoo Mail on Android 
 
  On Mon, 26 Oct 2020 at 9:22, Mrakobes666<notifications@github.com> wrote:   


please!

**Comment by Mrakobes666** [comment]
I also ask the developer to do this

**Comment by spacesynth2020** [comment]
Thank you

Sent from Yahoo Mail on Android 
 
  On Tue, 27 Oct 2020 at 11:48, Mrakobes666<notifications@github.com> wrote:   


I also ask the developer to do this

**Comment by Otiel** [comment]
Fixed in v1.3.4 thanks to @Nebula-Mechanica.

Sorry for the delay guys!
