### ISSUE TITLE
App Not Working

### ISSUE THREAD

**Issue by asterik22** [Otiel/BandcampDownloader#153]
When trying to download albums or single tracks the download is failing.  Is anyone else having this issue?

**Comment by wondergirlAmazon** [comment]
Yep, Bandcamp have changed some sort of  settings , it wont even let me download an individual track  ,it was working yesterday 22/09/2020

**Comment by asterik22** [comment]
I love this application so I hope they are able to get it functioning again.

**Comment by abbeyroad7** [comment]
Was definitely working this morning but looks like it's down now.

**Comment by Andreyjp93** [comment]
Says "could not retrieve album info for *link*"

**Comment by wondergirlAmazon** [comment]
I tried another extension I have on Chrome and that can't generate a download either so its definitely bandcamp, wish  I was code savvy.

**Comment by Otiel** [comment]
Hi guys, thanks for reporting this. Bandcamp has changed the metadata on their pages, thus the app cannot find the tracks to download anymore.

I'll have a look asap if this can be fixed easily. Hopefully they've let their data open. 🤞

**Comment by katla88** [comment]
Please do find a solution as to we depend on you

**Comment by Otiel** [comment]
I've just released [v1.3.3](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.3.3) which should fix the issue. Please let me know if you find any other bug, I might have missed some changes!
