### ISSUE TITLE
Discography option still not functioning

### ISSUE THREAD

**Issue by Purplepanther1234** [Otiel/BandcampDownloader#155]
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/5276827/BandcampDownloader.log)
The same error, even in the new update still occurs, no Discography can be found

**Comment by Otiel** [comment]
Will fix in the next version.

Sorry, time is scarce currently.

**Comment by buzniak** [comment]
Unfortunately can confirm as Otiel already knows Discography still not working, man this is the best app out there! Back to DL one at a time, better than nothing :D

**Comment by profucius** [comment]
Looking forward to the next version release, I'm also waiting for discog dls

**Comment by tylerS0887** [comment]
just commenting to say its an issue for me as well, looking forward to when and update comes but not rush, time is scarce for us all atm!

**Comment by wondergirlAmazon** [comment]
If it helps,ive found a workaround for now, which is to use a chrome store add on call **link grabber** which lets you copy past all the links to download without copying them one by one

**Comment by profucius** [comment]
Thanks! And for anyone who uses Firefox: "link gopher"

This isn't an ideal solution, but it is a workaround enough until Otiel can resolve

**Comment by Otiel** [comment]
Fixed in [v1.3.4](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.3.4). Sorry for the delay guys!
