### ISSUE TITLE
HTML characters not decoded properly

### ISSUE THREAD

**Issue by Svinhugg** [Otiel/BandcampDownloader#157]
Hi there is a issue in the latest version where the save in tag option can't tag the `'` character correctly, instead it's named something like this `&#39;s`

What to do?

![issue](https://user-images.githubusercontent.com/18412596/94254016-6f567a80-ff26-11ea-8633-f374279278f3.png)

**Comment by Otiel** [comment]
Thanks! I will have a look.

**Comment by Svinhugg** [comment]
It's still issue with this bug

**Comment by profucius** [comment]
This is referenced in #164 as well

**Comment by Otiel** [comment]
Fixed in [v1.3.5](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.3.5)
