### ISSUE TITLE
Fail converting character codes into characters.

### ISSUE THREAD

**Issue by kacciocciacciara** [Otiel/BandcampDownloader#158]
I downloaded the following album:
https://robesofsnow.bandcamp.com/album/ostaras-lake

The title is "Ostara's Lake". The title of the album on both folder placeholder and MP3 metadata is "Ostara&##39;s Lake", single hashtag.
The decimal 39 ascii char is the single quote ( &##39; single hashtag ), it seems it doesn't get converted from Unicode (or something similar) to plain char.

I'm using version 1.3.3.

**Comment by kacciocciacciara** [comment]
![Immagine 2020-09-29 133533](https://user-images.githubusercontent.com/51698511/94553363-b7440d00-0258-11eb-91cb-794f3e187144.png)

**Comment by Otiel** [comment]
Duplicate #157
