### ISSUE TITLE
Download all albums from one artist

### ISSUE THREAD

**Issue by ajsnyde** [Otiel/BandcampDownloader#16]
Oftentimes, I find myself wanting to download all of an artists discog, but have to paste in dozens of albums to do so. I'd like a way to simply paste the main page of an artist, and for the albums all to be downloaded automatically,

**Comment by ajsnyde** [comment]
Enhancement

**Comment by Otiel** [comment]
I had forgotten that I already implemented this. 😄 

Just check the "☑ Force download of all albums" option. I've modified the code in order to support track pages as well for this option, thanks to your commit cca782a6debb1a0c5d5a8e9c213c0fbab3cec7a7.

![screenshot](http://i.imgur.com/VwjcqLW.png)

**Comment by Otiel** [comment]
I've made some changes in [v0.1.7.1](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.7.1) in order to clarify the option available to download the artists discography.

Also fixed a bug that I introduced when adding the support for track pages from this option. 😕
