### ISSUE TITLE
Virus detected?

### ISSUE THREAD

**Issue by Dragon911XX** [Otiel/BandcampDownloader#162]
Seems like I'm getting the same issue that was occurring on issue #97. Potentially false positive

![Screenshot_3](https://user-images.githubusercontent.com/7053735/97767966-a7387b00-1aed-11eb-97cc-8b21e2b2224e.png)

![Screenshot_4](https://user-images.githubusercontent.com/7053735/97767969-aacc0200-1aed-11eb-896a-92ae205b43d7.png)

**Comment by Otiel** [comment]
Thanks for the report.
Please let me know your Antivirus Version (Windows Security > About) so that I can push this to Microsoft.

**Comment by Dragon911XX** [comment]
![image](https://user-images.githubusercontent.com/7053735/97777016-0b356080-1b3b-11eb-90f4-e7623be12896.png)

**Comment by Otiel** [comment]
I haven't received any answer from Microsoft (they usually answer within a week or two).

Can you tell me if this is resolved on your machine?

**Comment by Otiel** [comment]
I'm considering this resolved. Feel free to re-open the issue if you still have a threat found using Windows Defender.
