### ISSUE TITLE
Cover questions and Sign problem bug！

### ISSUE THREAD

**Issue by xingyundeyu** [Otiel/BandcampDownloader#164]
【‘=S&#39; 】Symbol garbled
Unable to download cover page
Hope to solve these problems，thinks

**Comment by Otiel** [comment]
Can you share the URL you're trying to download?

**Comment by xingyundeyu** [comment]
> 您可以共享您要下载的URL吗？

https://djshustryi.bandcamp.com/album/new-style-vol-3-free-download

Hope to solve the problem

**Comment by xingyundeyu** [comment]
> 您可以共享您要下载的URL吗？

![Uploading QQ截图20201101233030.jpg…]()
![Uploading QQ截图20201101233030.jpg…]()

**Comment by xingyundeyu** [comment]
> 您可以共享您要下载的URL吗？

![33](https://user-images.githubusercontent.com/73733274/97807239-b4df3380-1c9a-11eb-9850-d5a93282cda6.jpg)

**Comment by profucius** [comment]
I too am experiencing this issue on multiple albums. Here is an example of one of mine:

https://ddrkirbyisq.bandcamp.com/album/all-in-a-days-work-5

![image](https://user-images.githubusercontent.com/18254607/98384991-76d86b80-201c-11eb-9efa-bb1608a99e1d.png)

**Comment by Otiel** [comment]
Duplicate #157
