### ISSUE TITLE
Broken Program

### ISSUE THREAD

**Issue by FininhoRn** [Otiel/BandcampDownloader#165]
![image](https://user-images.githubusercontent.com/71853240/97812756-6a41c500-1c62-11eb-9029-fa4d28fecb34.png)
When I try to download it gives error and asks to contact here.

**Comment by Otiel** [comment]
Can you share the log file?

**Comment by FininhoRn** [comment]
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/5471651/BandcampDownloader.log)

**Comment by Otiel** [comment]
Thanks. Can you share your settings file as well?

**Comment by FininhoRn** [comment]
Sure, but how can I do it?

**Comment by Otiel** [comment]
You should have a BandcampDownloader.ini file next to the exe.

**Comment by FininhoRn** [comment]
I'm not able to uploading the file, I opened it in the notepad and I'll send you what's described there.

DownloadsPath=C:\Users\Felipe Sousa\Music\{artist}\{album}
DownloadArtistDiscography=true
AllowedFileSizeDifference=0.05
DownloadMaxTries=7
DownloadRetryCooldown=0.2
DownloadRetryExponent=4
SaveCoverArtInFolder=true
CoverArtFileNameFormat={album}
CoverArtInFolderConvertToJpg=true
CoverArtInFolderResize=false
CoverArtInFolderMaxSize=1000
SaveCoverArtInTags=true
CoverArtInTagsConvertToJpg=true
CoverArtInTagsResize=true
CoverArtInTagsMaxSize=1000
DownloadOneAlbumAtATime=false
RetrieveFilesSize=true
CheckForUpdates=true
EnableApplicationSounds=false
ShowVerboseLog=false
Language=pt
Theme=Dark
Proxy=System
ProxyHttpAddress=
ProxyHttpPort=0
CreatePlaylist=false
M3uExtended=true
PlaylistFormat=m3u
PlaylistFileNameFormat={album}
FileNameFormat={tracknum} {artist} - {title}.mp3
ModifyTags=true
TagAlbumArtist=Modify
TagAlbumTitle=Modify
TagArtist=Modify
TagComments=Empty
TagLyrics=Modify
TagTrackNumber=Modify
TagTrackTitle=Modify
TagYear=Modify

**Comment by Otiel** [comment]
You are missing two backslashes in the download path. Change it as such:

`DownloadsPath=C:\Users\Felipe Sousa\Music\{artist}\{album}`

**Comment by FininhoRn** [comment]
Okay, thanks for making the program available and giving us support whenever we need it.
