### ISSUE TITLE
Add option to not overwrite previously existing files

### ISSUE THREAD

**Issue by profucius** [Otiel/BandcampDownloader#167]
Feature request:

When downloading albums, discographies especially, the user may only be updating a pre-existing folder structure with the newest album(s)/single(s) from that artist. However, when downloading, BandcampDownloader currently overwrites all previously existing files, even when their name and tags are exactly the same.

Solution:

**Add an option checkbox in the program settings to allow ignoring/skipping songs if the filename is 1:1 as expected.** 

This would obviously skip any updating of tags, etc, but it would certainly be better than downloading multiple gigabytes every time an artist's discography needs to be updated locally.

**Comment by Otiel** [comment]
BandcampDownloader should do this check already. What's your value of this setting?

![image](https://user-images.githubusercontent.com/3851902/98385618-77d6c080-204f-11eb-9c05-4575ec9484cc.png)

**Comment by profucius** [comment]
I've tried any value, default 5, all the way up to 100, and it still re-downloads the files, even though they are in the same folder from just being downloaded moments ago.

**Comment by Otiel** [comment]
Can you share your log file please?

**Comment by Otiel** [comment]
Oops I just read that you already reported this issue in the past. I must have missed it at the time, sorry. Closing this one, duplicate #124.
