### ISSUE TITLE
Make the file naming scheme configurable

### ISSUE THREAD

**Issue by StefH** [Otiel/BandcampDownloader#17]
Now it's always `{track} {artist} - {title}`

It would be nice if it's configurable.

**Comment by ajsnyde** [comment]
I'll get to work on that in the next couple of days.

**Comment by ajsnyde** [comment]
I made some super-simple configuration options available in the following pull request:
https://github.com/Otiel/BandcampDownloader/pull/20

**Comment by ajsnyde** [comment]
If you want any other options, let me know. I am 90% sure that the basics should cover your desires, but it's not too hard to add more complex tags.

**Comment by Otiel** [comment]
Thanks @ajsnyde, published a [new release](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.7.0) with your changes.
