### ISSUE TITLE
Make a synology package of BandcampDownloader

### ISSUE THREAD

**Issue by dagger64** [Otiel/BandcampDownloader#174]
Hello,
it's a great app and i love it.
I have got a Synology always connected and i'd love to be able to download with my syno :).
Do you think it could be possible ?
Thank you a lot.

**Comment by Otiel** [comment]
Thanks for the kind words and the suggestion.

Unfortunately, a Synology package is not planned at all. That's a totally different operating system and would require most code to be rewritten.
