### ISSUE TITLE
An Unhandled error occurred

### ISSUE THREAD

**Issue by katla88** [Otiel/BandcampDownloader#175]
An Unhandled error occurred, an error message i receive after i updated the software, cant download anymore. please assist.

Thank you
![Capture112](https://user-images.githubusercontent.com/71809037/106375477-04fe8c80-6395-11eb-871f-bf488d7857db.JPG)

**Comment by Otiel** [comment]
Can you share your log file please?

**Comment by Otiel** [comment]
Closing as missing information. Please reopen with the log file if you wish.
