### ISSUE TITLE
Albums failing to save lyrics in metadata

### ISSUE THREAD

**Issue by ShadowClonier** [Otiel/BandcampDownloader#176]
When downloading an album, the lyrics no longer save into metadata. I've tested with some albums which prior have downloaded lyrics, but no longer achieves that successfully. Albums themselves still download normally, but now without the lyrics available on the Bandcamp page. Singles have maintained their lyrics intact from what I've been able to tell.

**Comment by internet-person** [comment]
can confirm, have had this issue myself

**Comment by Otiel** [comment]
Fix will be included in the next version
