### ISSUE TITLE
It's not possible to download single tracks

### ISSUE THREAD

**Issue by StefH** [Otiel/BandcampDownloader#18]
For example when I copy-paste this url `https://petergundry.bandcamp.com/track/a-wizards-dream`, the error message is like:

> Could not retrieve album info for https://petergundry.bandcamp.com/track/a-wizards-dream

**Comment by ajsnyde** [comment]
I've pinpointed and corrected this issue. The HTML for single tracks provides JSON metadata much like that for albums, but with a few null values (ex. track number). These nulls cannot be deserialized into objects without a setting or two that allows for that handling. You can find the fixed version here:
https://github.com/Otiel/BandcampDownloader/pull/20
https://github.com/Otiel/BandcampDownloader/commit/cca782a6debb1a0c5d5a8e9c213c0fbab3cec7a7

**Comment by Otiel** [comment]
Thanks @ajsnyde! I just fixed the track number that was set to "00" for the track pages. I think it makes more sense if the track number is "01" even when there's only one track.

I published a [new release](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.7.0) with your changes.
