### ISSUE TITLE
Unable to download album with non-english symbols.

### ISSUE THREAD

**Issue by Fr4Ckt3r** [Otiel/BandcampDownloader#186]
So when i try to download album, which name isn't english, its unable to retrive cover art.
Probably due its name being written on japanese.
Album that i encounter issue: https://fixions.bandcamp.com/album/-
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/6872267/BandcampDownloader.log)

**Comment by Fr4Ckt3r** [comment]
Seems that issue is happening due dumb totalitarian government i have in Russia. Their DPI blocks bandcamp image server due being badcoded.

**Comment by Otiel** [comment]
Thanks for the report! So you confirm only the cover art fails to be downloaded?
