### ISSUE TITLE
Cannot download albums while any "save cover" option is checked, stuck at "Computing size for album"

### ISSUE THREAD

**Issue by SamuelBucher** [Otiel/BandcampDownloader#187]
Pretty much what the title says. It was possible in the past on the latest version, but now for some reason it isn't. Isn't exclusive to a specific album. Not being able to download the cover isn't catastrophic, but still a bummer.

Log: 
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/6872800/BandcampDownloader.log)

**Comment by SamuelBucher** [comment]
Wait, no, Strawberry music player still displays album covers, even though I unchecked them. I guess there is no issue then.

**Comment by Otiel** [comment]
The error shown alerts that the file size of the cover could not be retrieved before downloading it, thus the progress bar will be slightly wrong. But I confirm you that the cover art is correctly downloaded. This is not ideal though, I need to fix this.

Issue has already been reported on #185, I'm gonna let this one closed.
