### ISSUE TITLE
FATAL System.IO.IOException The process cannot access the file

### ISSUE THREAD

**Issue by MrMagistrate** [Otiel/BandcampDownloader#188]
[BandcampDownloader.0.log](https://github.com/Otiel/BandcampDownloader/files/6913452/BandcampDownloader.0.log)
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/6913453/BandcampDownloader.log)
The discography I tried to download https://illuminatedpaths.bandcamp.com/music

**Comment by MrMagistrate** [comment]
[BandcampDownloader.ini.log](https://github.com/Otiel/BandcampDownloader/files/6914602/BandcampDownloader.ini.log the ini that causes the ioexception
I was able to get the download to complete by removing "{artist} - " from my FileNameFormat
probably has something to do with length of file name

**Comment by Otiel** [comment]
Thanks for the report!

**Comment by Otiel** [comment]
Closing as duplicate #141
