### ISSUE TITLE
Code improvement suggestions

### ISSUE THREAD

**Issue by StefH** [Otiel/BandcampDownloader#19]
Hello @Otiel, here are some code-improvements what you can make:

* use the ` async` and `await` pattern, this make code much easier to read and you don't need to use any `ContinueWith` statements anymore.

* use HttpClient instead of WebClient ; it's newer and has better async support

* use ` CancellationToken` instead of `userCancelled`

* format the code more like it's used in the .NET / C# world : like the `{` on a new line, and use the primitive like `string` instead of `String` and `bool` instead of `Boolean`.  I guess you come from the Java world?

If you need some help, just ask me.

**Comment by Otiel** [comment]
>* use the async and await pattern, this make code much easier to read and you don't need to use any ContinueWith statements anymore.

>* use HttpClient instead of WebClient ; it's newer and has better async support

>* use CancellationToken instead of userCancelled

Good suggestions there. I started writing the code when I didn't know of `async`/`await`, that is why they're not used in the code today. But you are right that they are cleaner, I will see if I have the time to modify this.

>format the code more like it's used in the .NET / C# world : like the { on a new line, and use the primitive like string instead of String and bool instead of Boolean. I guess you come from the Java world?

Nope, I dislike Java. 😄 I just find my code more readable when the `{` are on the same line, and I don't like that the syntax color used for `string` and `bool` is not the same that for all other types. Just my personal preferences there. 😃

**Comment by Otiel** [comment]
I took a look at the changes proposed here. Commenting to remember my searches.

* [`System.Net.Http.HttpClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) [doesn't](https://github.com/dotnet/corefx/issues/6849#issuecomment-195962260) seem to implement progress tracking (which is currently done using [`WebClient.DownloadProgressChanged`](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.downloadprogresschanged)). One solution would be to implement our [own progress tracking](https://stackoverflow.com/q/20661652/825024) ([best implementation?](https://stackoverflow.com/a/43169927/825024)). Not sure I want to go down this road right now... 😕 
* There is also [`System.Web.Http.HttpClient`](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient) ([differences](https://stackoverflow.com/q/31291008/825024)) which seem to support progress tracking, but it's for UWP apps. 👎 
* [`WebClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient) doesn't fully support the Task-based asynchronous pattern, so `CancellationToken` has to be attached [differently](https://stackoverflow.com/a/13811357/825024) from the usual. But it's doable. 👍

**Comment by Otiel** [comment]
>use the ` async` and `await` pattern, this make code much easier to read and you don't need to use any `ContinueWith` statements anymore.

Done

>use HttpClient instead of WebClient ; it's newer and has better async support

Won't do. See previous comment (no built-in progress tracking).

>use ` CancellationToken` instead of `userCancelled`

Done.

>`{` on a new line

Won't do (for now). My personal preference.

>use the primitive like `string` instead of `String` and `bool` instead of `Boolean`

Done.
