### ISSUE TITLE
Settings are not saving between sessions

### ISSUE THREAD

**Issue by DougRocket** [Otiel/BandcampDownloader#192]
Since one of the more recent updates 'settings' don't appear to be saving, and have to be specified every time the application is opened. This seems to be the case for all settings, such as theme, download location, cover art, etc.

This was never an issue with earlier versions of the application.

Thank you for your amazing work!

**Comment by Otiel** [comment]
There has been no change in regards to settings management for a long time. The settings file is saved next to the `BandcampDownloader.exe` file. Where did you save this file? If it's in an administrator location (like `C:\Program Files` for instance), that may the cause for your issue.

Thank you for the kind words. ❤️

**Comment by DougRocket** [comment]
Thank you, you're right! I've moved the file location and the application is working perfectly again.

Thanks for taking the time to respond 👍
