### ISSUE TITLE
Endless "Computing size for album..."

### ISSUE THREAD

**Issue by Andreyjp93** [Otiel/BandcampDownloader#199]
It just keeps computing size for album... forever

**Comment by 89z** [comment]
please provide example URL

**Comment by Otiel** [comment]
Some ISP are blocking the CDN hosting the cover arts: see #185 

Could it be your case?

**Comment by Andreyjp93** [comment]
> Some ISP are blocking the CDN hosting the cover arts: see #185
> 
> Could it be your case?

Yep, it worked. Thanks
