### ISSUE TITLE
Track Cannot Download

### ISSUE THREAD

**Issue by SpaceMacce** [Otiel/BandcampDownloader#201]
So I have been using This for a while but now when i go to download a track i get this message: 

Could not retrieve data for https://macintoshpluss.bandcamp.com/track/--#"><span class="track-title

I just want to knw if anybody else has had this issue.

**Comment by 89z** [comment]
please provide example URL

**Comment by SpaceMacce** [comment]
Oh my bad my internet went down during downloading causing this message to pop up  now it works perfectly fine.Sent from my Galaxy
-------- Original message --------From: Zombo ***@***.***> Date: 9/2/22  10:35 am  (GMT+10:00) To: Otiel/BandcampDownloader ***@***.***> Cc: SpaceMacce ***@***.***>, Author ***@***.***> Subject: Re: [Otiel/BandcampDownloader] Track Cannot Download (Issue #201) 
please provide example URL
