### ISSUE TITLE
Downloader just pauses?

### ISSUE THREAD

**Issue by Pigeon43** [Otiel/BandcampDownloader#202]
I was about 95% done on a download of around 7GB when the downloader just stopped, saying that the download speed was 0.0 kB/s.

This has happened twice, originally I thought it was just my crappy computer and its connection.

EDIT: It still says in Settings that it is downloading ("Some settings cannot be changed while tracks are downloading").

<img width="968" alt="Capture1" src="https://user-images.githubusercontent.com/68453978/154317853-b61637b7-c007-4e44-9e4c-1f8a8520881d.PNG">

Also, do I now need to restart the entire download, or can it resume somehow? :)

**Comment by Otiel** [comment]
You can start the same download, it will check the existing files and not download them again if they're correctly downloaded.

**Comment by Otiel** [comment]
There may be a bug if your downloads are stuck repeatedly, can you share your log file please?

**Comment by Pigeon43** [comment]
Hey sorry, just seen this. I'm sorry it's too late now, but this bug hasn't happened since. Maybe it was just a poor connection/connection drop. :)

**Comment by Otiel** [comment]
Thanks for the feedback, glad it's working ok now!

**Comment by Joduai** [comment]
Just wanted to check if anyone posted an issue with freezing/choking during download.
Seems like with huge amount of computed download after getting a lot of data the transfers are "choked" serverside. 
I've also looked into logs. Everything seems to be ok, no problems, just indicating that all files are correctly  downloaded and saved.

**Comment by Otiel** [comment]
@Joduai I need to implement a better download service to check to cases and be able to warn the user that something has gone wrong serverside. It's on my todo-list, unfortunately I don't have much time on my hands.

**Comment by Joduai** [comment]
understandable, if you got enough spare time, we'd get new features long time ago ;)

Still just pointing the thing if somebody gets into troubles to let him know everything's fine with app.
