### ISSUE TITLE
cant dl from bandcamp

### ISSUE THREAD

**Issue by werana1** [Otiel/BandcampDownloader#204]
cant dl any album from bandcamp, its start month ago , i update in 1.4.0 , please help
![Безымянный](https://user-images.githubusercontent.com/20840249/155871611-75a6051b-1615-40d7-9da9-bfd2b8de3275.png)
download only art and stop

**Comment by Otiel** [comment]
Please share your settings and log files.

**Comment by werana1** [comment]
here 
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/8148393/BandcampDownloader.log)

**Comment by Otiel** [comment]
Unfortunately I cannot reproduce this. Do you have the same issue when HTTPS is enabled, thus this option **unchecked**?

![Clipboard-20220227](https://user-images.githubusercontent.com/3851902/155898945-756b15c8-45f3-48e8-af0a-8880cd75f65d.png)

**Comment by werana1** [comment]
yes , i try different method, not work( i turn off my vpn same not work(

**Comment by Otiel** [comment]
And you can browse Bandcamp and listen to music directly on the website without any issue?

**Comment by werana1** [comment]
> And you can browse Bandcamp and listen to music directly on the website without any issue?

yes, now listen https://atomicflame.bandcamp.com/album/do-it-compilation-japanese-edition?from=hp

**Comment by werana1** [comment]
he stack 
![Безымянный](https://user-images.githubusercontent.com/20840249/155935796-543ecf1e-3739-48b1-87ca-2d6cabc03d54.png)

**Comment by werana1** [comment]
![234](https://user-images.githubusercontent.com/20840249/155936609-962b3e3a-419c-4714-9db0-cda7b4021066.png)
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/8151137/BandcampDownloader.log)

**Comment by Otiel** [comment]
Can you access to this track URL from your browser?

https://t4.bcbits.com/stream/bbf0d09f7235930325f733eb36c57e88/mp3-128/3423937261?p=0&ts=1646116890&t=72df2db9e8daa371888f47cb8686b2233587b4e8&token=1646116890_f7f00c2f96b7ec1ff5ef2671f9ba94eba44890cf

**Comment by werana1** [comment]
> Can you access to this track URL from your browser?
> 
> https://t4.bcbits.com/stream/bbf0d09f7235930325f733eb36c57e88/mp3-128/3423937261?p=0&ts=1646116890&t=72df2db9e8daa371888f47cb8686b2233587b4e8&token=1646116890_f7f00c2f96b7ec1ff5ef2671f9ba94eba44890cf

yes

**Comment by werana1** [comment]
solved! avast blocked!

**Comment by Otiel** [comment]
Great! 🎉
