### ISSUE TITLE
Downloader not working

### ISSUE THREAD

**Issue by kokoropop** [Otiel/BandcampDownloader#211]
Downloader not working for 2 days. I'm from Russia and maybe it binds with state policy for blocking internet resources? My log and preferences:

[pref.txt](https://github.com/Otiel/BandcampDownloader/files/8304759/pref.txt)
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/8304738/BandcampDownloader.log)

**Comment by Joduai** [comment]
with current regulations toward internet isolation of russia your best bet is to use vpn
Nothing else you can do, as bandcamp is hosted in usa.

ps. App is working without problems

**Comment by kokoropop** [comment]
Everything OK right now.
