### ISSUE TITLE
Select discography albums to download

### ISSUE THREAD

**Issue by andrienko** [Otiel/BandcampDownloader#219]
Maybe, would be nice, when downloading discography, to have option to exclude some of the albums (maybe via a modal with listbox or something, maybe activated by separate button or just an option).

Right now, whenever I want to skip some albums (when downloading discography fails on some albums) I am using the snippet:
```javaScript
console.log([].map.call(document.querySelectorAll('.music-grid-item.square a'), a => a.href).join("\r\n"))
```
(I just paste it into console and it gives list of URLs, I can then paste these to window and erase unwanted ones from there. Maybe will be useful for someone...)

**Comment by Otiel** [comment]
Thanks for the idea! 👍 

That's actually something I have in mind, but I need to do a lot of refactoring before starting to implement this. One day maybe...

**Comment by Otiel** [comment]
Duplicated #210
