### ISSUE TITLE
Freeze and crash because of cover

### ISSUE THREAD

**Issue by jarredou** [Otiel/BandcampDownloader#22]
Cover of this page make BD freeze and crash : https://sketismusic.bandcamp.com/album/hartyga-project-feat-andrey-bardin-fugue-for-steppe-and-organ-skmr-133

![bcdl2](https://cloud.githubusercontent.com/assets/6044199/22403892/59b5ab56-e625-11e6-9ada-4be8964fddc4.png)

If "Save in tags" or "save in folder" is checked, it will crash, if no cover download, it is working.

**Comment by Otiel** [comment]
Ugh, why use so long title names... The error occurs because the file BandcampDownloader tries to save has a path with more than 256 characters.

I'll make a fix.

**Comment by deadmans96** [comment]
i think this problem rises from 2 days ago , maybe they changed something on website

**Comment by deadmans96** [comment]
change the download path to a shortened one , like for example : E:\\Downloads
that's why for 256 Chars

**Comment by deadmans96** [comment]
the problem arises when the the song title is much bigger while the others still be downloadable

**Comment by Otiel** [comment]
I've implemented a fix in [release 0.1.9.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.9.0).
