### ISSUE TITLE
FATAL System.IO.IOException The process cannot access the file

### ISSUE THREAD

**Issue by tylerS0887** [Otiel/BandcampDownloader#233]
a context box pops up, "An unhandled error occured. The Application will close now."
attached is my log
as of now i am downloading albums individually and it's having no troubles.

[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/9945591/BandcampDownloader.log)

**Comment by Otiel** [comment]
Thanks for the report. I suspect this is a random bug and it shouldn't happen every time.

**Comment by Otiel** [comment]
Closing as duplicate #141
