### ISSUE TITLE
Could not retrieve data for https://...

### ISSUE THREAD

**Issue by Gee83** [Otiel/BandcampDownloader#236]
Hello,

Please open link below to see my current issue on windows 10 URL.
I've also attached my log file. 
 
![Data issue](https://user-images.githubusercontent.com/120699359/208020377-a4c2a7c1-9dff-4a2e-9941-c778d717fa24.png)
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/10242663/BandcampDownloader.log)

**Comment by Otiel** [comment]
No issue here. Can you access this album from your browser and listen to the songs?

I see that BandcampDownloader cannot check for updates on your screenshot, is your Internet connection ok?

**Comment by Gee83** [comment]
Yes I can, no problems.  My internet connection is fine too....

**Comment by Otiel** [comment]
Why BandcampDownloader cannot check for updates ? Is there a filtering solution preventing it from accessing to internet?

**Comment by Gee83** [comment]
I don't think so, I'll check it now

**Comment by Gee83** [comment]
Yes that's where the problem was. Bitdefender app had the setting on "not allowed".  It's working fine now.  Cheers :-)
