### ISSUE TITLE
Unhandled Error Im using Ubuntu OS

### ISSUE THREAD

**Issue by KaniMy2** [Otiel/BandcampDownloader#239]
![Screenshot from 2023-01-26 18-13-12](https://user-images.githubusercontent.com/123702068/214971676-06311d0e-b555-4a1c-b955-d098e1afd5f2.png)
![Screenshot from 2023-01-26 18-13-12](https://user-images.githubusercontent.com/123702068/214971712-b3a9cf69-d81a-492a-87bf-673b60d7f36f.png)

**Comment by Otiel** [comment]
The application does not support Linux, it only runs on Windows.
