### ISSUE TITLE
Application no longer functions

### ISSUE THREAD

**Issue by Saffron355** [Otiel/BandcampDownloader#247]
I used this program to download music successfully on September 8th of 2023, when I use it exactly one month later it no longer functions. It cannot check for updates, and it cannot download any music.

**Comment by Otiel** [comment]
It works fine here. Is your Internet traffic regulated maybe?

**Comment by Saffron355** [comment]
The problem turned out to be Kaspersky Total Security. I deactivated the program and the downloader worked as intended. I appreciate your quick response.
