### ISSUE TITLE
Download FLAC/WAV from Bandcamp, when it's free

### ISSUE THREAD

**Issue by arsinclair** [Otiel/BandcampDownloader#250]
Don't know if it has already been discussed before, so forgive me if I missed a thread.

How about downloading the music in the highest quality, when it's available? Many artists provide their music free of charge on Bandcamp. For example, https://astrangelyisolatedplace.bandcamp.com/album/2023-label-compilation-mixed-by-todos.

It would be nice to be able to use one tool for two things.

**Comment by Otiel** [comment]
#58

**Comment by arsinclair** [comment]
Okay, so mine is a duplicate. Closing :)
