### ISSUE TITLE
Another attempt to run the BandcampDownloader on Windows 7

### ISSUE THREAD

**Issue by alabx** [Otiel/BandcampDownloader#259]
I opened this thread because the previous one is closed.

I was looking for the solution for your program and somewhere I found an interesting topic about VxKex.
Otiel do you think this could help to run successfully your program via compability mode? 
I'm little suspicious about programs like these, especially when I see warnings about fake repositories. Maybe could you try it in your free time on your virtual machine?
There are two links I found, but I don't know if there are any differences:
https://github.com/i486/VxKex/releases
https://github.com/commandcontrolQ/VxKex/releases

**Comment by Otiel** [comment]
This program is detected as Trojan by Windows 10 virus protection and Windows 7 smartscreen. I'm not taking any risk, feel free to test yourself.

(I closed issue #256 because I can't fix the issue, but comments are not closed, we can still exchange messages on #256 if it's on-topic)

**Comment by alabx** [comment]
OK, I'm not sure it is the original one I saw people recommended.

**Comment by Tindalos** [comment]
I've been using VxKex on my 7 for ages now, it's very safe.

Was ineffectual for getting BCD to successfully download.  Likely because it mostly sorts graphics and .DLL stuff rather than IP stuff.
