### ISSUE TITLE
Add an option to skip track size estimate

### ISSUE THREAD

**Issue by Otiel** [Otiel/BandcampDownloader#27]
It will save some time when you're trying to download lots of albums, plus it should help with the Bandcamp anti-spam filter. If the option is checked, the progress should be calculated on the number of tracks instead of their size.

Suggested by @zontargs on #26.

**Comment by ajsnyde** [comment]
Let me know if you're working on this - I might implement that enhancement for you..

**Comment by Otiel** [comment]
I am not at the moment. You can take this task if you want. Thanks!

**Comment by ajsnyde** [comment]
I've completed an option that allows for this:
https://github.com/ajsnyde/BandcampDownloader/commit/f914011fc44cd8b2df53e06981690ff7b3c81eaf

**Comment by Otiel** [comment]
Thanks @ajsnyde! Merged and included in the new release [v0.1.9.2](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.9.2).
