### ISSUE TITLE
Stop scrolling the log to bottom when the caret is not at the end

### ISSUE THREAD

**Issue by Otiel** [Otiel/BandcampDownloader#29]
Currently the log is constantly scrolled to the end when the download is being done, which prevent users to read the log with ease. This will allow users to read the top part of the log even when it's still being populated.

**Comment by ajsnyde** [comment]
Added that functionality:
https://github.com/ajsnyde/BandcampDownloader/commit/62a4c75f580cd7f7bfef42eaa588fdba11cc520e

**Comment by ajsnyde** [comment]
Correction, I added an autoscroll button. Had a little trouble with the caret, and it seemed like more trouble than it was worth.

**Comment by Otiel** [comment]
Thanks @ajsnyde! Merged and included in the new release [v0.1.9.2](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.9.2).
