### ISSUE TITLE
Won't download

### ISSUE THREAD

**Issue by ajsnyde** [Otiel/BandcampDownloader#3]
Not sure what the problem is. I get the error:

17:18:11 Retrieving album data for shook.bandcamp.com/album/shook-album
17:18:11 Could not retrieve data for shook.bandcamp.com/album/shook-album

This is true with all other info that I tried.

**Comment by Otiel** [comment]
Did you try entering the following URL: https://shook.bandcamp.com/album/shook-album?

It works for me:

![screenshot](https://cloud.githubusercontent.com/assets/3851902/13542801/c38081ba-e265-11e5-8843-5e0bc6e04736.png)

**Comment by ajsnyde** [comment]
Thanks tons! I somehow didn’t manage to get the http prefix to each site. Retrying, it all works.

**Comment by Otiel** [comment]
Great, glad to know it works for you now!
