### ISSUE TITLE
Add an option to limit the number of parallel connections

### ISSUE THREAD

**Issue by Otiel** [Otiel/BandcampDownloader#30]
It should help to prevent tripping the Bandcamp anti-spam filter.

Suggested by @zontargs on #26.

**Comment by ajsnyde** [comment]
With the current version, there is an exponential back-off strategy that limits the spammed attempts. Not sure if this alone is sufficient. I'll check into how easily the feature could be added, and might work something out.

**Comment by Otiel** [comment]
Closing this as the existing exponential back-off mechanism seems to be enough to prevent tripping the Bandcamp anti-spam filter.

Please comment if you feel it could still be of use.
