### ISSUE TITLE
Downloads not completing

### ISSUE THREAD

**Issue by sebw1nters** [Otiel/BandcampDownloader#31]
Just in the past couple of days, all attempted downloads using this tool stop at "Computing size for '[album name]'...".  They never complete.

**Comment by Otiel** [comment]
I trust you are using the latest release (0.1.8.0). Are you using the [exponential back-off mechanism](https://github.com/Otiel/BandcampDownloader/wiki/Settings-file#content)? If so, what values are you using?

**Comment by kyoet** [comment]
Seems like there is a problem with Cover Art... it stucks always at "Computing size for album " but when i untag the "save in tags" option then it downloads

**Comment by Otiel** [comment]
It seems that Bandcamp decided to add https to all their pages. That caused an issue when downloading the cover arts.

The [new version 0.1.9.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.9.0) fixes it. Thanks for reporting this guys!
