### ISSUE TITLE
Tracks no longer saving within an album folder

### ISSUE THREAD

**Issue by quzks** [Otiel/BandcampDownloader#32]
I switched from an old version to 1.8.0 to get the artwork fix, but my new version downloads all the tracks to the destination folder without creating an album folder. The file destination is the same as in my old version. Pictured is my destination folder, with examples of albums from the old version and one from 1.8.0
![capture](https://cloud.githubusercontent.com/assets/28363386/25678291/3a359ffc-3017-11e7-80ac-83c03baffb79.JPG)

**Comment by Otiel** [comment]
Can you indicate the downloads location ("Save albums to") you are using? Are you correctly using the `{artist}` and `{album}` placeholders?

**Comment by quzks** [comment]
Ah, no I do not see those, what would the correct format look like? "SaveAlbumsTo": "{artist} {album}",  ?

**Comment by Otiel** [comment]
Yes, I mean in the application. The behavior was changed in version 0.1.5.2, this is why it isn't working for you now.

Now, you have to set the download location to "C:\Users\Joe\Desktop\Bandcamp Downloader\{artist}\{album}".

You can also use the texts {year}, {month} and {day} for the release date if you want. Check the tooltip on the "Save albums to" textbox, it explains it.

**Comment by quzks** [comment]
Thank you very much, please continue your awesome work.

**Comment by Otiel** [comment]
You're welcome!

I'll try. 😉

**Comment by 07416** [comment]
@quzks I recommend using `{artist} - {album}` to separate the artist and the album title.
