### ISSUE TITLE
"Failed to retrieve album info" error message 

### ISSUE THREAD

**Issue by Siouq** [Otiel/BandcampDownloader#33]
For the past 24hours when I have tried to download an album I receive this message and I am unable to download anything (I receive this message for every album i attempt to download).

Example:
23:27:47 Could not retrieve album info for https://strangeranger.bandcamp.com/album/big-krackel

I am on version 1.8 and as far as I know I am not doing anything wrong. Ive had great success with this in the past so either way thank you for your work.

**Comment by Otiel** [comment]
This should be fixed in the [new version 0.1.9.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.9.0). Thanks for reporting this and for the kind words. 😄

**Comment by Siouq** [comment]
Everything is in working order with version 1.9! Thank you very much
