### ISSUE TITLE
Unable to download tracks with unusual whitespace characters in the track information

### ISSUE THREAD

**Issue by zontargs** [Otiel/BandcampDownloader#34]
Example: http://bandcamp.analoguetrash.com/track/phuturist-echo-images-stormtrooper-remix

The whitespace in "Phuturist​	​(Echo" is a zero-width space (U+200B), a tab (U+0009), and another zero-width space (U+200B). Attempts to download the file fail:

08:20:42 Starting download...
08:20:42 Retrieving album data for http://bandcamp.analoguetrash.com/track/phuturist-echo-images-stormtrooper-remix
08:20:43 Computing size for album "Phuturist	(Echo Image's Stormtrooper Remix)"...
08:20:43 Retrieved the size of the MP3 file for the track "Phuturist	(Echo Image's Stormtrooper Remix)"
08:20:43 Downloading track "Phuturist	(Echo Image's Stormtrooper Remix)" from url: http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=2af1939bced1e7cdb993563c87dc5e81&id=1245385054&stream=1&ts=1495031685.0
08:20:43 Unable to download track "01 Goteki - Phuturist	(Echo Image's Stormtrooper Remix).mp3" from album "Phuturist	(Echo Image's Stormtrooper Remix)". Try 1 of 7
08:20:44 Unable to download track "01 Goteki - Phuturist	(Echo Image's Stormtrooper Remix).mp3" from album "Phuturist	(Echo Image's Stormtrooper Remix)". Try 2 of 7
08:20:46 Cancelling downloads. Please wait...
08:20:47 Unable to download track "01 Goteki - Phuturist	(Echo Image's Stormtrooper Remix).mp3" from album "Phuturist	(Echo Image's Stormtrooper Remix)". Try 3 of 7
08:20:47 Downloads cancelled by user

**Comment by Otiel** [comment]
I've published a [new version](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.9.1) that fixes this. Thanks for reporting it!
