### ISSUE TITLE
folders

### ISSUE THREAD

**Issue by PALLET48** [Otiel/BandcampDownloader#36]
hello ,

       may I pick your brains,  I love this program but it has changed slightly over the last few releases.

      I cannot fathom how folders are created now . 
 
      
![downloaders](https://user-images.githubusercontent.com/24648801/26914987-07c4b7d0-4c1c-11e7-9174-51cc96dd2646.png)
before the example above would have created folders  and mp3 in them .but now it just creates mp3

inside the folder of saves album to eg C:\Users\stuart hemmings\Downloads\Born Bad Records

any help would be greatly appreciated

cheers

stu

hope this makes sence

**Comment by Otiel** [comment]
Hi,

When you hover your cursor over the "Save albums to" textbox, there's a tooltip displayed with all the placeholders you can use:

![image](https://user-images.githubusercontent.com/3851902/26915390-24285dbe-4c26-11e7-971c-605d7968f740.png)

The value you're probably looking for is `C:\Users\stuart hemmings\Downloads\{artist}\{album}`.

If you want to add the year in the album folder, you can try `C:\Users\stuart hemmings\Downloads\{artist}\{year} {album}`. Possibilities are endless. 😄 

And if you want your options to be remembered across sessions, hit the "Save" button!
