### ISSUE TITLE
One-track downloading issue

### ISSUE THREAD

**Issue by sebw1nters** [Otiel/BandcampDownloader#38]
When you download a single track, the year on the downloaded .mp3 file is saved as "1" instead of the correct release year.

**Comment by ajsnyde** [comment]
Could not reproduce with the following url:
https://vegetables-belarus.bandcamp.com/track/feeling-sorry-for-us
Download yielded one mp3 with year as 2014.
Any chance you could give the url in question that is giving the problem?

**Comment by Otiel** [comment]
I could not replicate this as well. As asked by @ajsnyde, can you share the URL you are using, as well as the string for the download folder (censor any username if needed)?

**Comment by Otiel** [comment]
Closing this since we don't have enough information to reproduce. Please do comment if the error happens again.
