### ISSUE TITLE
Download files in lossless format

### ISSUE THREAD

**Issue by Atom88884444** [Otiel/BandcampDownloader#4]
A great feature to add to this already amazing application would be the ability to download in other formats, such as Apple Lossless or FLAC, either through downloading these formats directly from Bandcamp (if they keep these formats on their site) or by converting the mp3 files after they have been downloaded. Thank you very much for such a great program!

**Comment by Otiel** [comment]
Hi,
Unfortunately, Bandcamp does not offer to stream the music in a better quality than 128kbps mp3. As BandcampDownloader is simply retrieving the streamed files, it cannot download files in a better quality.

As for the converting the mp3 files to a lossless format, I don't see the point. You would just end up with a larger file (FLAC or ALAC), but with no more quality than the original MP3. Is there any particular reason you would like to convert the MP3 to a lossless format?

**Comment by Atom88884444** [comment]
Thanks for the reply. I guess my main reason for my wanting lossless formats is just for consistency with the rest of my library and because I prefer lossless files, although there really isn't any base to my wanting them. I'm just a crazy perfectionist. Thanks anyway for your program and just ignore my dumb request.

**Comment by Otiel** [comment]
No worries, I understand the need for consistency and perfection. :smiley: 
Thanks for the kind words anyway and do not hesitate if you have another feature request!

**Comment by LennyPenny** [comment]
Sorry for opening this issue again: 
How about albums I own on bandcamp? 
Would adding a credential feature to this and downloading things I own on bandcamp in the highest quality offered be in scope for this tool in the far future?

**Comment by Otiel** [comment]
Please open a new issue to track this request.

I'm not saying "no" right now, I'll have to see if it's feasible and what efforts it requires.
