### ISSUE TITLE
Could not retrieve album info for https://buerak.bandcamp.com/

### ISSUE THREAD

**Issue by st4ycool** [Otiel/BandcampDownloader#43]
https://i.imgur.com/824hzzz.jpg

I tried to download with latest available version. =(
Solved by feeding one link per album of this artist. 
FYI: I ve seen this error before.

**Comment by Otiel** [comment]
If you provide an URL that is not an album URL, you have to check the "☑ Download artist discography" option.

**Comment by st4ycool** [comment]
thank you! Sorry

**Comment by Otiel** [comment]
No worries. 😄
