### ISSUE TITLE
App simply crashes on getting artwork for a song, while trying to download entire album

### ISSUE THREAD

**Issue by rpmsauron** [Otiel/BandcampDownloader#44]
For example, while trying to download the following album:
https://nostro.bandcamp.com/album/nostromo
it simply crashes with no further notice.
I'm running it on Windows 7 x64 with 6gb RAM.
It seems to be related to the image converter.

Some images (probably the ones being retrieved as it crashes) become like the attached image file (cropped halfway).

My settings are as follows (copied from the local settings file previously saved):

`
{
  "ConvertCoverArtToJpg": true,
  "CoverArtMaxSize": "1000",
  "DownloadOneAlbumAtATime": false,
  "DownloadsLocation": "C:\\Users\\Rui\\Desktop\\{artist}\\{album}",
  "DownloadArtistDiscography": true,
  "ResizeCoverArt": false,
  "SaveCoverArtInFolder": true,
  "SaveCoverArtInTags": false,
  "ShowVerboseLog": false,
  "TagTracks": true,
  "DownloadMaxTries": 7,
  "DownloadRetryCooldown": 0.2,
  "DownloadRetryExponential": 4.0,
  "AllowableFileSizeDifference": 0.05,
  "FilenameFormat": "{tracknum} {artist} - {title}.mp3"
}
`

![rise](https://user-images.githubusercontent.com/7701410/32015839-2d995054-b9ba-11e7-90d5-285444999516.jpg)

**Comment by Otiel** [comment]
This is not due by the image converter, but simply because you checked "☑Download artist discography" while the artist has only one album. Duplicate with #21.

Try unchecking the "☑Download artist discography" option.
