### ISSUE TITLE
Add option to change the file naming scheme from the GUI

### ISSUE THREAD

**Issue by Otiel** [Otiel/BandcampDownloader#46]
Currently, we can change the file naming scheme by playing with the following setting:
`"FilenameFormat": "{tracknum} {artist} - {title}.mp3"`

It would be nice if we could change it from the interface.

**Comment by ajsnyde** [comment]
Hmm, I might get to that sometime in the next week.

**Comment by ajsnyde** [comment]
Well, its been a week 😉, and I got it done (and much, much, more):
https://github.com/Otiel/BandcampDownloader/pull/52/

**Comment by Otiel** [comment]
Released in [0.2.0.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.0.0)
