### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by AziasYur** [Otiel/BandcampDownloader#5]
I've been using this program for a while and one thing that I think is missing is a config file.
It could prevent you from selecting the output folder or check the options every time you start the it.
And thank you for this awesome program.
Edit: I'm sorry for the label, I couldn't find where i had to choose it.

**Comment by Otiel** [comment]
That makes sense, I will work on that.

(I think you cannot add any label to an issue, only I can)

**Comment by Otiel** [comment]
I've added some logic to save/load settings to a file. Using the new button, you can save the settings to a file that will be located next to the `BandcampDownloader.exe` file, and they will be automatically loaded the next time you start the application.

Please grab the [latest version](https://github.com/Otiel/BandcampDownloader/releases) to try it. Let me know what you think.

![untitled](https://cloud.githubusercontent.com/assets/3851902/14311832/b2de173a-fbe9-11e5-979f-fc8c4f9d8144.png)
