### ISSUE TITLE
Possible spin-off from this project

### ISSUE THREAD

**Issue by ajsnyde** [Otiel/BandcampDownloader#50]
mixcloud.com can likely be used in a similar fashion as bandcamp for song downloads. It only makes sense to use a fork of this UI to allow for that. See http://www.mixcloud-downloader.com/ for a working example of a working example.

**Comment by Otiel** [comment]
I'm not sure what you're suggesting. Are you saying that it would be a good idea to be able to download songs from Mixcloud by using BandcampDownloader?

**Comment by ajsnyde** [comment]
@Otiel, possibly, yes. Probably outside the scope of this repo though. The downloading mechanism would change a small amount, but otherwise the UI and settings would likely be identical.

**Comment by Otiel** [comment]
Forks are encouraged of course. I don't want to modify BandcampDownloader to work with other websites for now, because other softwares do it already good enough.

**Comment by ajsnyde** [comment]
Oh, that's what I was trying to convey - I would never want to combine the services within one UI unless there was an active need for it.
