### ISSUE TITLE
Crash when downloading

### ISSUE THREAD

**Issue by shadoxxhd** [Otiel/BandcampDownloader#54]
When trying to download https://bluestahli.bandcamp.com/ discography (Settings: all on except Download one album at a time, save cover in folder and verbose log) the app crashes while downloading (some files created). Tested with v0.1.9.2 and v0.1.9.3.

**Comment by Otiel** [comment]
I'm unable to reproduce this. Can you please paste here the log shown, after checking the option "Verbose log"?

**Comment by shadoxxhd** [comment]
I just had the same problem again - sometimes it occurs, sometimes it doesn't. Sadly "Verbose" logging seems to provide no useful information concerning the problem.
https://imgur.com/a/KmFHGgT

**Comment by Otiel** [comment]
Log file has been added in v0.2.0.0. Can you try again and provide your `BandcampDownloader.log` if the issue arises?

You mention unicode characters. I still can't reproduce the bug by downloading [this track](https://shirobon.bandcamp.com/track/ft-protodome) (titled `(ﾉ◕ヮ◕​)​ﾉ​*​:​･ﾟ✧ ft. Protodome`) for instance. Can you try it (uncheck ☑"Download artist discography", it shouldn't have any consequence) and let me know if it fails for you?

Also, which version of Windows 7 are you using?

**Comment by gchilds11** [comment]
same issue. https://imgur.com/40HBmLk https://pastebin.com/ebT577Pp  https://pastebin.com/cRi9ffsU problem occurs when 2 or more albums are downloaded though occasionally single albums do not download.

**Comment by gchilds11** [comment]
for instance: downloading [sleep until it hurts you](https://liluglymane.bandcamp.com/album/sleep-until-it-hurts-you) causes a crash while downloading [the weeping worm](https://liluglymane.bandcamp.com/album/the-weeping-worm) results in a success. it appears it occurs on albums with less tracks as [trick dice](https://liluglymane.bandcamp.com/album/trick-dice) fails while [three sided tape vol 1](https://liluglymane.bandcamp.com/album/three-sided-tape-volume-one) succeeds with no errors.

**Comment by Otiel** [comment]
Thanks, I've been able to reproduce it. Fix coming next version...
