### ISSUE TITLE
Crashes under Windows XP

### ISSUE THREAD

**Issue by habuvo** [Otiel/BandcampDownloader#6]
I tried on a different albums with the same result.
Screenshot attached
![screen](https://cloud.githubusercontent.com/assets/19569819/17665568/7a9f1b76-6304-11e6-8ae6-7d0419370ec7.png)

**Comment by Otiel** [comment]
Could you paste here the error message? Maybe in English? Is there some stack trace available on the crash dialog?

**Comment by habuvo** [comment]
It's from Win event log:

EventType clr20r3, P1 bandcampdownloader.exe, P2 0.1.5.0, P3 5704d060, P4 imageresizer, P5 3.4.3.103, P6 536ba65b, P7 228, P8 1e, P9 system.io.filenotfoundexception, P10 NIL.

BandcampDownloader.exe
Platform version: v4.0.30319
System.IO.FileNotFoundException

in ImageResizer.Configuration.Config..ctor(ImageResizer.ResizerSection)
in ImageResizer.Configuration.Config.get_Current()
in BandcampDownloader.MainWindow+<>c__DisplayClass9_1.<DownloadCoverArt>b__1(System.Object,  System.ComponentModel.AsyncCompletedEventArgs)
in System.Net.WebClient.OnDownloadFileCompleted(System.ComponentModel.AsyncCompletedEventArgs)
 in System.Net.WebClient.DownloadFileOperationCompleted(System.Object)
in System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
in System.Threading.ThreadPoolWorkQueue.Dispatch()
in System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Otiel** [comment]
I believe the error is due because you do not have .NET Framework 4 installed on your PC. Please make sure you have [.NET Framework 4](https://www.microsoft.com/en-us/download/details.aspx?id=17851) installed then try again.

**Comment by habuvo** [comment]
Yes, you absolutely right! I'm installed .NET and it works!
Thx for your app, it's great!

**Comment by Otiel** [comment]
Thanks :)
Glad to know it's fixed for you.
