### ISSUE TITLE
Create folders for albums

### ISSUE THREAD

**Issue by justinwzig** [Otiel/BandcampDownloader#62]
It would be great if the ability to save tracks for a given album into a folder with some naming scheme (such as artist-album) was available. As of right now, it's a bit of a pain to decipher and move hundreds of tracks into album folders.

**Comment by M4lik** [comment]
This Feature ist already implemented, and should be the default case.

In the text box below the URL area you can specify the download path and with path elements like {album} or {artist you can sort them in specific folders. But as I said this should be the default case. 
My guess is that you have overwritten the default path forgot to add {artist}\{album} or something like that to the end.

**Comment by Otiel** [comment]
As said by @M4lik, you just have to use `{artist}` and `{album}` placeholders in the download location:

![image](https://user-images.githubusercontent.com/3851902/46280927-821f5a00-c56d-11e8-8623-2d6cdeda857f.png)

To reset your settings and use the default ones instead, you can delete the `BcDlSettings.json` file.
