### ISSUE TITLE
Pulling cover in maximum quality

### ISSUE THREAD

**Issue by roman412** [Otiel/BandcampDownloader#64]
At the moment there is a function to resize images to a fixed resolution (Constrain maximum width / height). Thus, if this checkbox is unchecked, it is expected that the program will download the image in maximum resolution. Nevertheless, the image is still downloaded reduced.

An example of this: https://mstrvlk.bandcamp.com/album/-
Image resolution to this EP: 3900x3900, and the image itself takes 5.4 mb.
The program downloads the artwork at a resolution of 1200x1200, plus JPEG Quality = 85%, thus, the image takes 145 kb. In the original image JPEG Quality = 100%.

Perhaps the problem is that you get links to download, like: https://f4.bcbits.com/img/a0613907443_10.jpg, however, you should know that the image on the bandcamp in its maximum quality is at https://f4.bcbits.com/img/a0613907443_0.jpg (notice the number zero and the number ten after the underscore).

For everything else - thanks, great program, which is pleasure to use.

**Comment by Otiel** [comment]
Thanks for reporting this, I'll have a look at it.

**Comment by roman412** [comment]
Looking ahead, if it is implemented, it is most likely to have the function to choose a quality of the image to insert into the tags of audio files, an image with standardized parameters, for example: 500x500, JPEG, 85%.

As far as I know, at the moment the image after being downloaded is directly inserted into the tags, thus, when downloading an uncompressed original image, the size of the output mp3 file increases significantly.

One of the biggest images on bandcamp I ever seen was 16.8 MB, so if we download an album of ten tracks, the output size of the folder with the album will increase by 168 MB (to the question of the need for the function to adjust the format of the image that is inserted into tags).

**Comment by Otiel** [comment]
>As far as I know, at the moment the image after being downloaded is directly inserted into the tags, thus, when downloading an uncompressed original image, the size of the output mp3 file increases significantly.

No, currently it is done in the following steps:

1. Download the image.
2. Convert it to jpg (if option checked).
3. Resize it (if option checked).
4. Save it to folder (if option checked).
5. Save it to tags (if option checked).

When saving the cover art to tags, the mp3 files should only grow the same size as the cover art file at step 4.

**Comment by roman412** [comment]
Yeah, that it is what I am talking about.
E.g. we want to download original cover art which is 16 MB, so for doing that the 'Resize' option have to be unchecked. That means, that the downloaded image (at the 4th step in your message) will be saved uncompressed and then inserted to the tags.

**Comment by Otiel** [comment]
I'm not sure I understand correctly. You want to:
* Download the cover art **uncompressed** in a folder, but at the same time,
* Save the cover art **compressed** in the mp3 tags.

Is that right?

**Comment by roman412** [comment]
Correct.
You see, if we insert the uncompressed image inside mp3 tags, the size of the album folder will bloat significantly. 
So in my opinion, having option to chose the quality and size of the image to insert to the tags apart from the option to chose what image will be saved to the folder is very useful.
What do you think on that? Do you agree?

**Comment by Otiel** [comment]
That makes sense. 👍

**Comment by Otiel** [comment]
Released in [0.2.0.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.0.0)
