### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by RichyZ99** [Otiel/BandcampDownloader#67]
It would be nice if this program was available in other languages or, at least, one could modify the messages in an easy way

**Comment by Otiel** [comment]
Thanks for the suggestion.

Would you be willing to participate to the translation via a pull request?

**Comment by RichyZ99** [comment]
Of course I am: since I'm Italian, I can provide that translation (sorry for the long time to reply, but I have been AFK for a while)

**Comment by Otiel** [comment]
First I have to design and implement a multi-language architecture. 😀 

I'll inform you when it's ready of course.

**Comment by RichyZ99** [comment]
Ok, thanks

Il mar 4 dic 2018, 17:04 Otiel <notifications@github.com> ha scritto:

**Comment by Simonwep** [comment]
Could also provide translations, but in German if wanted :)
Thank's btw for this great app, It's awesome!

**Comment by Mrthomas20121** [comment]
i can provide translations in french if wanted. love the app!

**Comment by simon511000** [comment]
Me too, in french ;)

**Comment by Mohnraa** [comment]
I can also provide translations in Spanish (Latin american), if wanted

**Comment by Otiel** [comment]
Version [0.2.6.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.6.0) is out now, the first localized version! Translated in English (of course) and French for now.

If you wish to help translate in another language, please see the [guidelines](https://github.com/Otiel/BandcampDownloader/blob/v0.2.6.0/docs/help-translate.md). For now, you'll have to edit the _resx_ files. I'll see if we can use a project such as Weblate to make the process more user-friendly.

Thanks all for offering your help and don't hesitate to chime in should you have any issue translating!

(@Mrthomas20121 & @simon511000 thanks for offering your help for the french translation but I had to translate the app in one language first to test the architecture, French was my only choice available 😋)

**Comment by Simonwep** [comment]
@Otiel Currently working on a German translation :) Will open a PR later.

**Comment by Otiel** [comment]
Translation can now be done via [Weblate](https://hosted.weblate.org/engage/bandcampdownloader) which should be easier to manage for translators.

[![Translation status](https://hosted.weblate.org/widgets/bandcampdownloader/-/287x66-white.png)](https://hosted.weblate.org/engage/bandcampdownloader)

For the existing languages (german and italian), you can for example have an easy access to the missing translations: hit the "Translate" button, and voilà!

![image](https://user-images.githubusercontent.com/3851902/58430757-f84b7080-80aa-11e9-8a6a-a034ccae9132.png)

You can also watch the project on Weblate and choose to receive notifications when there's new strings to translate.

Thanks for your help in any past or future translations!

**Comment by RichyZ99** [comment]
> Translation can now be done via [Weblate](https://hosted.weblate.org/engage/bandcampdownloader) which should be easier to manage for translators.

I corrected some typos in the Italian translation

**Comment by Otiel** [comment]
Thanks. That'll land in the next version, soon.
