### ISSUE TITLE
Could not retrieve data from albums without cover

### ISSUE THREAD

**Issue by silkky** [Otiel/BandcampDownloader#69]
![otiel](https://user-images.githubusercontent.com/45414873/49131806-52b07380-f2b8-11e8-86dc-8f6b7dbf6f9c.PNG)
cant download https://afterdarkrecordings.bandcamp.com/album/adr-unreleased-tracks
i think is because the album dont had cover. i can download any album with Cover art from this artist without problem, but testing with other 3 albums without cover of the same artist cant download.

**Comment by Otiel** [comment]
Thanks for reporting this. It is indeed due to the missing cover art.
