### ISSUE TITLE
"Failed to retrieve the size of the MP3 file for the track" and "Unable to download track"

### ISSUE THREAD

**Issue by Cicida** [Otiel/BandcampDownloader#7]
I keep getting a certain error for SOME of the tracks I try to download.
03:34:56 Failed to retrieve the size of the MP3 file for the track "Ontal, Fausten - Terraform (feat. Fausten)". Try 4 of 10
"03:35:15 Unable to download track "07 Negative A - Freebase.mp3" from album "Grand Theft Audio". Try 1 of 10"
However that second one seems to only affect certain tracks of certain albums.
Is it a form of anti-spam or something? I'm trying to download over 150 albums at once and the first time I tried to download, I'd forgotten to replace http:// with https:// and the total size was 3300mb, but now it's down to 665mb.
Anyway, Not sure what's going on. Maybe you have some insight into it.
PS. Thanks for this handy thing.

**Comment by Otiel** [comment]
I've experienced the same when downloading a lot of albums in a short period of time (be it in the same session of BandcampDownloader or not - restarting the application doesn't help). I suppose as well that it is a way for Bandcamp to prevent the kind of downloads we do, as you're not supposed to listen to hundreds of songs in a few seconds/minutes. The only thing I can tell you is wait between downloads.

But that shouldn't affect only specific songs, try again by downloading only the regarded album.

Replacing `http://` by `https://` in your album urls shouldn't change anything, as the program is using the `http` protocol anyway to download tracks.

**Comment by NeonLightning** [comment]
could this be fixed by adding an option to add a delay between track downloads?

**Comment by Otiel** [comment]
An exponential back-off has been implemented since this issue was closed. Did you try playing with [these settings](https://github.com/Otiel/BandcampDownloader/wiki/Settings-file#content)?
