### ISSUE TITLE
Add proxy option

### ISSUE THREAD

**Issue by wthreex** [Otiel/BandcampDownloader#70]
Hi there, I'm living in a country which banned bandcamp website, it would be nice you guys add proxy option (sock5) to it thanks...

**Comment by Otiel** [comment]
Hi,

>deezer

This app is for Bandcamp only.

**Comment by wthreex** [comment]
sorry that's typo

**Comment by Otiel** [comment]
_BandcampDownloader_ already supports the system proxy. Did you try setting a proxy in Windows settings?

**Comment by wthreex** [comment]
Excuse me what are you mean system proxy?I just seen a "Save current setting" button,  I'm using Tor Bundler Proxy which means an internal proxy to use it on another apps, it's not tunnel all internet traffic like VPNs, I know if i use a VPN to tunnel all my traffic BandcampDowloader will works fine, But my goal is only tunnel BandcampDownloader if there is a option for that,The tor bundler gives a internal proxy like 127.0.0.1:9050, so inside the app must be an option to put that adress:port like every proxy over the internet.

**Comment by wthreex** [comment]
I know this, I dont want tunnel all my traffic trough a proxy on LAN setting(As some of website out there need my actuall ip, it's really risky to me)

So if you mind, Add option that could handle external proxies like most popluar app like mozilla: https://malzo.com/i/2018/12/07/h5h.png

With this method, it is possible to use spcific proxy only on this app.

**Comment by Otiel** [comment]
Got it. I'll see what I can do. 👍

**Comment by wthreex** [comment]
Awesome! Note that it would be nice this option support all protocol like HTTP, Socks5, HTTPS etc...

**Comment by Otiel** [comment]
First version will be HTTP / SSL only.

SOCKS is a little more tricky...

**Comment by Otiel** [comment]
Can you try the [new version](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.2.0) and let me know if it works with a HTTP proxy?

**Comment by wthreex** [comment]
Yeap. Works very well, See my screen record:

https://dbr.ee/vktc

Much Appreciated!

**Comment by Otiel** [comment]
Thanks for the feedback.

Closing this for now. I'll revisit the SOCKS option if there is more demand.
