### ISSUE TITLE
Add {album} placeholder to file name format

### ISSUE THREAD

**Issue by Joduai** [Otiel/BandcampDownloader#72]
howdy
I miss an {album} option in file name format
Sometimes I join couple albums under 1 directory to copy it on mp3 player and adding an album name to all files during download would come in handy.

**Comment by Joduai** [comment]
howdy
I miss an {album} option in file name format
Sometimes I join couple albums under 1 directory to copy it on mp3 player and adding an album name to all files during download would come in handy.

**Comment by Otiel** [comment]
Thanks for the suggestion, that's a good idea.

**Comment by Otiel** [comment]
Implemented in [0.2.4.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.4.0)

**Comment by chambermx** [comment]
Hello you can add an option to save the cover album with diferent name?

Thanks
