### ISSUE TITLE
Cannot download tracks with short name (1-3 characters)

### ISSUE THREAD

**Issue by SkyreVentes** [Otiel/BandcampDownloader#75]
https://angellust.bandcamp.com/track/--3
doesn't seem to download the track nor album art for it, however it does create the folder.
just seems to stop at "computing size for album "♥"..."
perhaps it could be the -'s in the url or the character used for the album name?

**Comment by Otiel** [comment]
Thanks for reporting this, I'll have a look at it.

**Comment by Otiel** [comment]
Fixed in [0.2.4.2](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.4.2)
