### ISSUE TITLE
Windows Defender quarantines 0.2.4.2 & 0.2.5.0

### ISSUE THREAD

**Issue by celynwalters** [Otiel/BandcampDownloader#76]
Windows Defender is quarantining [v0.2.4.2](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.4.2) before I get a chance to run it.
The problem is reported as `Trojan:Win32/Azden.A!cl`.
Perhaps the cause of this was introduced in the dependencies updates?
I am running Windows 10 build 17763.316

**Comment by Otiel** [comment]
Thanks for reporting this.

It's probably a false positive. VirusTotal [screams 1/69](https://www.virustotal.com/#/file/7c7c2e387f38cdd0d5cdfdfec34e0c9730612140007370df853bfee1cb984d84/detection).

I'll have a look at the updated _dlls_ and see if anything pops up.

**Comment by Otiel** [comment]
This should be fixed in [v0.2.5.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.5.0)

VirusTotal now reports [0/69](https://www.virustotal.com/#/file/da23bf170689dfa1371495ddbbf5afde3543cde36ed15186345a936be760c9c8/detection):

![VirusTotal result](https://user-images.githubusercontent.com/3851902/54217012-1a414800-44eb-11e9-86db-d93ef4e47cc7.png)

**Comment by M4lik** [comment]
@Otiel sorry, but... [not anymore](https://www.virustotal.com/de/file/da23bf170689dfa1371495ddbbf5afde3543cde36ed15186345a936be760c9c8/analysis/1552580427/)

**Comment by Otiel** [comment]
@M4lik thanks for the warning.

I'll see how I can submit a false positive report to Microsoft - never had to do this before.

**Comment by celynwalters** [comment]
On the plus side, it seems fine if I build it myself 🤔

**Comment by Otiel** [comment]
@celynwalters I have no Windows Defender report as well on the machine I use to build it. I'm not sure how Windows Defender works, maybe it whitelists every _exe_ you build via Visual Studio?

**Comment by Otiel** [comment]
Case submitted to Microsoft. We'll see what they say.

**Comment by Otiel** [comment]
Got an answer from Microsoft, saying they've "removed the detection".

It seems all good on my machine now (threat definition version: 1.289.1250.0). VirusTotal is back to 0:

![VirusTotal screenshot](https://user-images.githubusercontent.com/3851902/54448781-d2b9f680-474c-11e9-9d3d-cd6fa607c509.png)

Can you let me know if you can run it now?

**Comment by celynwalters** [comment]
Nice - works perfectly for me.
Thanks!
