### ISSUE TITLE
Add option to customize the cover art file name (with placeholders)

### ISSUE THREAD

**Issue by chambermx** [Otiel/BandcampDownloader#77]
Hello you can add an option to save the cover album with diferent name? 

Thanks

**Comment by Otiel** [comment]
To make sure I understand, you'd like to be able to customize the cover album file name with placeholders like `{artist}`, `{album}`...?

**Comment by Otiel** [comment]
This has been implemented in [v0.2.7.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.7.0).

**Comment by chambermx** [comment]
Thanks Otiel
