### ISSUE TITLE
Process closes after completing download

### ISSUE THREAD

**Issue by CristenPerret** [Otiel/BandcampDownloader#79]
My download is complete when I have done my trial runs on this application, and the process closes on me. AFAIK it isnt crashing, my music seems intact. Could it matter that I changed my default file type to mp4?
Previously I had a Batch file I wrote to utilize the bandcamp-dl python command-line, and it just loops back to wait for the next link.
I tend to listen to albums on the go, and just paste it in, and download as I go.
Its really minor, but I would appreciate this a lot.
Maybe im just missing something, thanks for this application though its very clean, reminds me of MrS0m30n3's youtube-dl-gui

**Comment by Otiel** [comment]
>Could it matter that I changed my default file type to mp4?
That's exactly the reason. Only `mp3` is supported.

I will make some changes to force the file extension to `mp3` in order to prevent such errors.

**Comment by CristenPerret** [comment]
oh okay that makes more sense than what I assumed.
Glad I decided to add that into this post, cause initially I forgot about it and had to edit it back into this post.
Thank you for your timely response!
