### ISSUE TITLE
Alt+key shortcuts for buttons

### ISSUE THREAD

**Issue by lakecityransom** [Otiel/BandcampDownloader#81]
alt+key shortcuts for buttons. Example: Underscore S in "Start download". Alt+S hits the button.

**Comment by Otiel** [comment]
Thanks for the suggestion. Access keys / mnemonics (alt + key) are already available on every control of the application.

You can show them by default by enabling the "access key" option on Windows. For Windows 10 1809, it's under `Settings → Ease of Access → Keyboard → Underline access keys when available`:

![image](https://user-images.githubusercontent.com/3851902/56237374-268d6780-608c-11e9-91e4-dd48d4ccc947.png)

The access key for the "Start download" button is set to <kbd>Alt</kbd><kbd>d</kbd>:

![image](https://user-images.githubusercontent.com/3851902/56237296-f5ad3280-608b-11e9-9d45-ecf8696c4253.png)
