### ISSUE TITLE
Create m3u playlist

### ISSUE THREAD

**Issue by l0oo** [Otiel/BandcampDownloader#82]
Just an idea... 
IMHO would be nice to have such feature in BandcampDownloader.

**Comment by Otiel** [comment]
Thanks for the suggestion.

A few questions to identify how we should implement this:

1. Should we create one `m3u` file per album, regardless of the download path (even if all albums are stored in the same folder)?
2. Should we create a `m3u` file for albums containing only one track?
3. Should we create a `m3u` file for track pages (thus containing only one track) as well?
4. Where should we store the `m3u` file in case the download path contains placeholders (`{album}` for instance)? In the end folder?

**Comment by l0oo** [comment]
Hello Otiel!

Thank you for answer!
IMO the best would be create m3u file inside folder where album's mp3s are stored - so one per album. Some use {artist} - {album} ({year}), some {artist}/{album} - so it is universal imho. If all albums (you mean mp3 files?) are in same folder too - this way someone can play album he wants, without picking songs manually.

2. One track album
I think yes, as some albums are one track only, some are not complete (some have just two songs published of ten etc, anyway - numbers of tracks will be preserved in filenames thus m3u).

3. Track pages
Well - I guess yes. As finally those file(s) land in folder and have 'artist - title'.

4. {album}
Yup - IMHO in the end folder. As I wrote above.

BTW: There is nice small app where some problems with BOM are adressed.
http://www.dcmembers.com/skwire/download/splaylistmaker/
IMHO OK would be .m3u, UTF-8 (with BOM) - as some titles may have exotic diacritics etc...

Rgrds!

**Comment by Otiel** [comment]
>you mean mp3 files?

Yes that's what I meant.

Ok, I see we are on the same page, good! 👍 I'll start working on this when I find the time then.

Thanks for the link, I'll make sure "special" characters are supported as best as possible.

**Comment by Otiel** [comment]
Done in [v0.2.8.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.8.0). Let me know if that's good for you.

**Comment by l0oo** [comment]
On Wed, 24 Apr 2019 07:40:55 -0700
Otiel <notifications@github.com> wrote:

> Done in <https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.8.0
> Let me know if that's good for you.

Hello!
Thanks for 0.2.8.1 version and all your great work!
Unfortunately it is not good for me yet. ;)
I am using m3u only (even non ext. in fact) 
(BTW: maybe others formats are OK - dunno).

For better understanding, below m3us made by different apps:
LP: https://asunajanjelinek.bandcamp.com/album/signals-bulletin

BandcampDownloader normal m3u:

Relief, pt.1.mp3
Pulsating Primary Structure.mp3
Fountain.mp3
How a spiral works.mp3
Blinking of countless lines.mp3

BandcampDownloader ext m3u:

#EXTM3U
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:801,Relief, pt.1
Relief, pt.1.mp3
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:674,Pulsating Primary Structure
Pulsating Primary Structure.mp3
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:250,Fountain
Fountain.mp3
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:385,How a spiral works
How a spiral works.mp3
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:859,Blinking of countless lines
Blinking of countless lines.mp3

sPlaylistMaker: 
(NB my settings of this app in att., notice I set it to #EXTM3U in
options, not using this feature in fact, just for compatibility maybe):

#EXTM3U
01 ASUNA & Jan Jelinek - Relief, pt.1.mp3
02 ASUNA & Jan Jelinek - Pulsating Primary Structure.mp3
03 ASUNA & Jan Jelinek - Fountain.mp3
04 ASUNA & Jan Jelinek - How a spiral works.mp3
05 ASUNA & Jan Jelinek - Blinking of countless lines.mp3

As you can see - tracks in m3u needs to have full names of saved mp3
files. As my naming scheme for songs is: 
{tracknum} {artist} - {title}.mp3 
Created m3u must reproduce this scheme. :/ If not - files aren't played.
BTW: for downloading folder I use {artist} - {album} ({year})
Same for {artist} - {album} ({year}).m3u (reproduce name of folder)

So for this album it should look like this, in my case:

#EXTM3U
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:801,Relief, pt.1
01 ASUNA & Jan Jelinek - Relief, pt.1.mp3
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:674,Pulsating Primary Structure
02 ASUNA & Jan Jelinek - Pulsating Primary Structure.mp3
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:250,Fountain
03 ASUNA & Jan Jelinek - Fountain.mp3
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:385,How a spiral works
04 ASUNA & Jan Jelinek - How a spiral works.mp3
#EXTALB:Signals Bulletin
#EXTART:ASUNA & Jan Jelinek
#EXTINF:859,Blinking of countless lines
05 ASUNA & Jan Jelinek - Blinking of countless lines.mp3

PS
I have another small idea... :) As I like to read blogs where good
BC albums are mentioned, I have to copy its adress to clipboard, than
paste to BCDownloader and press download... Could you make optional
"watch for clipboard link" => when I copy BC link to clipboard it is
automatically transferred to BCDownloader and than download in
background... What do you think? Hope it is possible... 

-- 
rgrds!
l0oo

PS
FYI my BandcampDownloader.ini

DownloadsPath=D:\bc_music\{artist} - {album} ({year})
AllowedFileSizeDifference=0.05
DownloadMaxTries=7
DownloadRetryCooldown=0.2
DownloadRetryExponent=4
SaveCoverArtInFolder=true
CoverArtInFolderConvertToJpg=false
CoverArtInFolderResize=false
CoverArtInFolderMaxSize=1000
SaveCoverArtInTags=true
CoverArtInTagsConvertToJpg=true
CoverArtInTagsResize=true
CoverArtInTagsMaxSize=1000
DownloadOneAlbumAtATime=true
RetrieveFilesSize=true
CheckForUpdates=true
EnableApplicationSounds=false
ShowVerboseLog=false
Language=en
Proxy=System
ProxyHttpAddress=
ProxyHttpPort=0
FileNameFormat={tracknum} {artist} - {title}.mp3
ModifyTags=true
TagAlbumArtist=Modify
TagAlbumTitle=Modify
TagArtist=Modify
TagComments=DoNotModify
TagLyrics=Modify
TagTrackNumber=Modify
TagTrackTitle=Modify
TagYear=Modify
DownloadArtistDiscography=false
CoverArtFileNameFormat={album}
CreatePlaylist=true
M3uExtended=true
PlaylistFormat=m3u
PlaylistFileNameFormat={artist} - {album} ({year})

**Comment by Otiel** [comment]
>As my naming scheme for songs is: `{tracknum} {artist} - {title}.mp3`
>Created m3u must reproduce this scheme. :/ If not - files aren't played.

You are right. That's a bug. I'll fix this in the next version.

>I have another small idea...

Let's continue the discussion for this in #85.

**Comment by Otiel** [comment]
>You are right. That's a bug. I'll fix this in the next version.

It should be fixed in [v0.2.8.2](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.8.2)

**Comment by l0oo** [comment]
On Thu, 25 Apr 2019 10:01:22 -0700
Otiel <notifications@github.com> wrote:
> <<https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.8.2>0.2.8.2>https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.8.2>0.2.8.2
>  - Fixed the track path stored in playlist files. <<https://github.com/Otiel/BandcampDownloader/issues/82>#82>https://github.com/Otiel/BandcampDownloader/issues/82>#82 
Thank you for fixing tracks names. Works OK.
Now I have problem with diacritics and Foobar2000 (and maybe other
players). Files with diacritics are missing in player when starting
album from m3u playlist (only those without are present).
Check please e.g:
https://brzoskamarciniakmarkiewicz.bandcamp.com/album/wp-aw
According to Notepad3 sPlaylistMaker create "Unicode (UTF-8) Signature"
while BCD: "Unicode (UTF-8)" m3u and the 2nd brings to Foobar only those
mp3s which have no diacritics. Hope it can be fixed too. 
Rgrds!

**Comment by Otiel** [comment]
Thanks for the example URL. I'll check it out.

**Comment by Otiel** [comment]
New try: [v0.2.9.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.9.0)

It should fix the issue with foreign characters. Please let me know if all is ok for you now.

**Comment by l0oo** [comment]
On Sat, 04 May 2019 03:18:05 -0700
Otiel <notifications@github.com> wrote:

> New try: <https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.9.0>v0.2.9.0
>  It should fix the issue with foreign characters. Please let me know if all is ok for you now.

TYVM!
All is correct now!
