### ISSUE TITLE
Put each album into a folder when not choosing download discography

### ISSUE THREAD

**Issue by lakecityransom** [Otiel/BandcampDownloader#83]
As far as I can tell there is no option to put downloads into their own folders unless you tick get discography which is not always applicable to the operation at hand.

**Comment by Otiel** [comment]
You can do this by using the `{album}` placeholder in the download path, like: `C:\something\{artist}\{album}`

![screenshot](https://user-images.githubusercontent.com/3851902/56557955-4f868e80-659d-11e9-9ecd-f04e260eae52.png)

**Comment by lakecityransom** [comment]
My mistake TY!
