### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by psydex** [Otiel/BandcampDownloader#86]
I have not update Bandcamp Downloader from a long time so I decided to do so today but the newest version triggers Chrome and Windows Defender. Why?
![Screenshot_1](https://user-images.githubusercontent.com/5594251/56790057-2455a680-680c-11e9-9f30-5fa113106a99.png)

**Comment by m-lohmann** [comment]
Maybe their heuristics detected a false positive.

According to VirusTotal the file is clean: https://www.virustotal.com/gui/file/ec17f2c643bd24450d24b6ea7e6a3234e0158ccc022aae0cf73b587925766b30/detection

**Comment by Otiel** [comment]
That's a false positive. Already happened in the past. See #76 

VirusTotal reports [0/73](https://www.virustotal.com/#/file/ec17f2c643bd24450d24b6ea7e6a3234e0158ccc022aae0cf73b587925766b30/detection):

![image](https://user-images.githubusercontent.com/3851902/56790363-ab068580-6804-11e9-8455-db5a2f31b714.png)

**Comment by Otiel** [comment]
I will submit the false positive to Microsoft. Can someone indicate me the name of the detection? Is it `Trojan:Win32/Azden.A!cl` like on #76?

**Comment by psydex** [comment]
> Also, what is your virus definition version?

![Screenshot_1](https://user-images.githubusercontent.com/5594251/56870151-8f24fe80-6a13-11e9-8bf8-7324b222b7db.png)

**Comment by Otiel** [comment]
Thanks. Can you let me know the name of the detection reported by Windows Defender? I can reproduce it on my machines.

**Comment by DesireCampbell** [comment]
I'm getting the same error on version 2.10.0 (but previous versions download without error)  "Trojan:Script/Foretype.A!ml"  https://i.imgur.com/uDOAIX7.jpg
