### ISSUE TITLE
Cover art not saved in tags

### ISSUE THREAD

**Issue by pYbiz** [Otiel/BandcampDownloader#88]
Is there an option to save the artwork on the file?

**Comment by Otiel** [comment]
Yes: Settings > Cover art > Save cover art in tags

**Comment by pYbiz** [comment]
Yeah, i did that already but it didnt show any cover art on the file

**Comment by pYbiz** [comment]
![Untitled](https://user-images.githubusercontent.com/38293472/57561654-f1a6c480-735a-11e9-8adf-793b2b06a9a1.png)

**Comment by Otiel** [comment]
Indeed, seems like there's a bug in the latest version!

Thanks for reporting this, I'll fix it asap.

**Comment by Otiel** [comment]
I just published a new version where this should be fixed: [0.2.10.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.10.0)
