### ISSUE TITLE
Failed to retrieve the size of the cover art file

### ISSUE THREAD

**Issue by nvdwolk** [Otiel/BandcampDownloader#9]
Hi,

I'm getting this error with bandcamp downloader on different computers the last few days:

http://prntscr.com/cqlvp9

27 Failed to retrieve the size of the cover art file for album "BLK EDITS #2". Hit max retries of 10. Progress update may be wrong.

Do you have any idea what causes this error?

Thank you in advance!

Kind regards
Niels

**Comment by Otiel** [comment]
Is it an error you get 100% of the time? Is it happening only on the cover arts?

**Comment by nvdwolk** [comment]
Otiel,

I found it's only the cover art, sorry for not giving you this feedback.

Kind regards,
Niels



Met vriendelijke groet,

Niels van der Wolk

2016-10-07 10:53 GMT+02:00 Otiel <notifications@github.com>:

**Comment by Otiel** [comment]
That's weird. And it happens for all albums you try to download or some are successful?

**Comment by mentalbroadcast** [comment]
I have the same problem as nvdwolk and I can't dload any song or album.

It started few days ago...

**Comment by sparrowtimes** [comment]
Encountering the same issue as of this morning. I put two albums in the link and this is the result:

10:12:29 Computing size for album [ALBUM NAME]...
10:12:30 Failed to retrieve the size of the cover art file for album [ALBUM NAME]. Hit max retries of 10. Progress update may be wrong.
10:12:34 Computing size for album [ALBUM NAME]...
10:12:34 Failed to retrieve the size of the cover art file for album [ALBUM NAME]. Hit max retries of 10. Progress update may be wrong.

I've tried a few more times, restarting, etc, and it's replicated.

**Comment by Seraphim1138** [comment]
Same problem here it was working fine up until the 27th of September. Similar to sparrowtimes it won't download if save in folder or save in tags is checked.

**Comment by Otiel** [comment]
I'll have to look at that. Hopefully I will find the time soon but I can't make any promises right now, sorry.

**Comment by ajsnyde** [comment]
Getting same issue with version 0.1.4.3 - simply unchecking the album cover tag is a suitable workaround.

**Comment by mentalbroadcast** [comment]
Yeah, unchecking the album cover tag worked for me too.

**Comment by Otiel** [comment]
@dashWo fixed the issue, huge thanks to him!

I published a [new release](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.5.1) that includes his fix.

**Comment by mentalbroadcast** [comment]
Thank you both @dashWo & @Otiel

**Comment by mentalbroadcast** [comment]
Tnx to both of you!
