### ISSUE TITLE
Accept translations on Weblate

### ISSUE THREAD

**Issue by comradekingu** [Otiel/BandcampDownloader#94]
Half a viable translation was just sent down the drain to the tune of the policy of only accepting suggestions. That is a bad idea.
https://hosted.weblate.org/projects/bandcampdownloader/bandcampdownloader/nb_NO/
My user-account is https://hosted.weblate.org/user/kingu/
Ideally, direct editing of source strings would also help a lot.

**Comment by Otiel** [comment]
>only accepting suggestions

Thanks for reporting this, that was a wrong configuration from my part! This should be fixed now.

>Ideally, direct editing of source strings would also help a lot.

Alright, I've added back the [help file](https://github.com/Otiel/BandcampDownloader/blob/master/docs/help-translate.md#option-2-editing-the-translation-files) for editing the strings files.
