### ISSUE TITLE
Windows Defender "Virus Detected"

### ISSUE THREAD

**Issue by DesireCampbell** [Otiel/BandcampDownloader#97]
I'm getting an error trying to download version 2.10.0 (but previous versions download without error) "Trojan:Script/Foretype.A!ml" https://i.imgur.com/UMzlt4n.png 
 https://i.imgur.com/uDOAIX7.jpg

(This issue seems similar to https://github.com/Otiel/BandcampDownloader/issues/86 )

**Comment by Otiel** [comment]
Thanks for reporting this, I'll push this to Microsoft once again.

**Comment by Otiel** [comment]
Case pending at Microsoft. In the meantime, I confirm this is a false positive. You can check [VirusTotal](https://www.virustotal.com/gui/file/2638bb4e38288ee3273734d0bac3340be9068405fac9791902493dfda5a506b4/detection) as well which reports the file as safe:
![image](https://user-images.githubusercontent.com/3851902/58765059-0ef03c80-856f-11e9-975f-3fbe02b52445.png)

**Comment by DesireCampbell** [comment]
Thanks man!

**Comment by Otiel** [comment]
This is the answer I got from Microsoft:

>The file is not malware and we cannot reproduce any detection on the file. If detection is still observed, please follow the steps below to capture support log files from the system reporting detection.
>
>On Windows 10, from elevated command prompt, change to directory "%programfiles%\windows defender" and execute mpcmdrun.exe with option GetFiles: cd "%programfiles%\windows defender" mpcmdrun.exe -GetFiles
>
>On Windows 7, from elevated command prompt, change to directory "%programfiles%\microsoft security client" and execute mpcmdrun.exe with option GetFiles: cd "%programfiles%\microsoft security client" mpcmdrun.exe -GetFiles
>
>All created log files will be compressed into MPSupportFiles.cab.

Can you send me the MPSupportFiles.cab file as well as your virus definition?

**Comment by DesireCampbell** [comment]
Gmail doesn't want to attach the cab file for "security reasons". This link
should work:  http://desirecampbell.com/MPSupportFiles.zip

**Comment by Otiel** [comment]
Thanks, got it. What is your threat definition version?

**Comment by DesireCampbell** [comment]
Is that in "Windows Security > About"?

Antimalware Client Version: 4.18.1904.1
Engine Version: 1.1.15900.4
Antivirus Version: 1.293.2742.0
Antispyware Version: 1.293.2742.0

**Comment by Otiel** [comment]
Yes, perfect. Thanks, I will report this to Microsoft and let you know what they say.

**Comment by Otiel** [comment]
Answer from Microsoft:

>We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions. 
>
>1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>2. Run `MpCmdRun.exe -removedefinitions -dynamicsignatures`
>3. Run `MpCmdRun.exe -SignatureUpdate`
>
>If detection is still observed, please follow the steps below to capture fresh support log files from the system reporting detection. 
>
>On Windows 10, from elevated command prompt, change to directory "%programfiles%\windows defender" and execute mpcmdrun.exe with option GetFiles: 
>`cd "%programfiles%\windows defender"`
>`mpcmdrun.exe -GetFiles`
>
>On Windows 7, from elevated command prompt, change to directory "%programfiles%\microsoft security client" and execute mpcmdrun.exe with option GetFiles: 
>`cd "%programfiles%\microsoft security client"`
>`mpcmdrun.exe -GetFiles`
>
>All created log files will be compressed into MPSupportFiles.cab.

Can you try the first three steps in order to clear your cache and let me know if you can now run v0.2.10.0?

If it's still detected as a trojan, can you please share again the MPSupportFiles.cab file?

**Comment by DesireCampbell** [comment]
Done! No errors on this PC now - and I checked another PC (with updated
definitions) and no errors there either, hooray!

**Comment by Otiel** [comment]
Perfect, thanks for taking the time to test this!

**Comment by fxsmthn** [comment]
Hello,
it appears that Windows Defender is again detecting bandcampdownloader.exe as a trojan, this time its "Trojan:Win32/Emali.A!cl". The latest .exe to be specific, release 2.1.0. 1.1.0. doesn't get detected as anything. Checked virustotal and malwarebytes, they say the file is clean.

**Comment by Otiel** [comment]
Thanks! 👍 

I'll report this to Microsoft.

**Comment by Otiel** [comment]
Sorry, forgot to ask: what's your Antivirus Version (Windows Security > About)?

**Comment by fxsmthn** [comment]
Antimalware Client Version: 4.18.1905.4
Engine Version: 1.1.16100.4
Antivirus Version: 1.297.194.0
Antispyware Version: 1.297.194.0

Was at the time, now it doesn't seem to be picking up anything, after running windows update for latest definitions and the Cumulative.

Antimalware Client Version: 4.18.1905.4
Engine Version: 1.1.16100.4
Antivirus Version: 1.297.217.0
Antispyware Version: 1.297.217.0

Well then, apologies for wasting your time. 😅

**Comment by Otiel** [comment]
No problem! Still better to report this as this could happen to someone else.

Thanks for the feedback.

**Comment by thesyberian** [comment]
![image](https://user-images.githubusercontent.com/53040315/61445567-49167180-a956-11e9-85b6-ed0b13ca5eb7.png)


> No problem! Still better to report this as this could happen to someone else.
> 
> Thanks for the feedback.

And it did.

**Comment by Otiel** [comment]
@thesyberian Please let me know your Antivirus Version (Windows Security > About) so that I can report it to Microsoft.

**Comment by thesyberian** [comment]
> @thesyberian Please let me know your Antivirus Version (Windows Security > About) so that I can report it to Microsoft.

Antivirus Version: 1.297.1299.0

**Comment by Otiel** [comment]
Thanks. Submitted to Microsoft and they removed the detection.

Let me know if it happens again.
